<table style="width: 100%;height: 30px;margin: auto; font-family: \'Helvetica Neue\', Helvetica, Roboto, sans-serif !important;font-size: 13px;text-align: justify;">
    <tr>
        <td>
            <table style="position: relative;width: 100%;height: 30px;margin: auto;text-align: justify;">
                <tr style="background-color: black;font-weight: bold;border-collapse: collapse;">
                    <td>
                        <p style="color: white;"> 1.DATOS BÁSICOS</p>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <table style="position: relative;width: 100%;height: 30px;margin: auto;text-align: justify; font-size: 13px;" align="center">
                <tr>
                    <td width="40%">
                        <p><b>Nombre cuenta habiente:</b> <?php echo $name; ?></p>
                    </td>
                    <td width="20%">
                        <p><b>C.C.</b> <?php echo $document_number; ?></p>
                    </td>
                    <td width="40%">
                        <p><b>Fecha de Nacimiento:</b> <?php echo $birthdate; ?></p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p><b>Direccion:</b> <?php echo $address; ?></p>
                    </td>
                    <td>
                        <p></p> <b>Ciudad:</b> <?php echo $city; ?></p>
                    </td>
                    <td>
                        <p><b>Telefono celular:</b> <?php echo $phone; ?></p>
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <p><b>Correo Electronico:</b> <?php echo $email; ?></p>
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <p><b>Incremento anual IPC + 2% </b></p>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <p><b>Inscripción débito automático:&nbsp;</b> <?php echo $automatic_debit; ?></p>
                    </td>
                    <td>
                        <p><b>Banco:</b> <?php echo $bank; ?></p>
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <p><b>Franquicia:</b> <?php echo $franchise; ?></p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p><b>Fecha de vencimiento: &nbsp;&nbsp;&nbsp;</b> <?php echo $expiration_date; ?></p>
                    </td>
                    <td colspan="2">
                        <p><b>Numero de tarjeta:</b> <?php echo $card_number; ?></p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p><b>Cuenta:</b> <?php echo $account_type; ?></p>
                    </td>
                    <td colspan="2">
                        <p><b>Numero de Cuenta CTA:</b> <?php echo $account_number; ?></p>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <p><b>Beneficiario:</b> <?php echo $name; ?></p>
                    </td>
                    <td><b> C.C.</b> <?php echo $document_number; ?></td>
                </tr>
                <tr>
                    <td colspan="3"></td>
                </tr>
                <tr>
                    <td colspan="3">
                        <p><b>Cobro administrativo por pago en el counter:</b> $10.000 / $15.000</p>
                    </td>
                </tr>
                <tr>
                    <td>

                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <hr>
        </td>
    </tr>
    <tr>
        <td>
            <p><b>PRIMERO:</b> Manifiesto que he decidido tomar el plan de débito automático en el Club médico deportivo Bodytech y que acepto entregar los datos de mi tarjeta crédito y/o débito para que la compañía realice el débito mensual, conforme
                a mi plan y al contrato firmado entre las partes.</p>
        </td>
    </tr>
    <tr>
        <td>
            <p><b>SEGUNDO:</b>Es responsabilidad del AFILIADO mantener la información financiera vigente y con el crédito suficiente para cubrir los cargos. En caso de sustitución, revocación, vencimiento o remplazo de la tarjeta y/o cuenta, me obligo
                a informar al Club médico deportivo Bodytech los datos actualizados</p>
        </td>
    </tr>
    <tr>
        <td>
            <p><b>TERCERO:</b>BODYTECH no se hará responsable por cargos adicionales que el banco realice por la transacción de débito automático. Si en la oportunidad en que se realiza el cargo/débito a cargo del AFILIADO no hay fondos disponibles en
                la cuenta bancaria o en la tarjeta de crédito, el PRESTADOR podrá realizar el débito nuevamente cuando existan fondos disponibles en ella. En caso de mora, el PRESTADOR podrá debitar de la cuenta bancaria o de la tarjeta de crédito
                del AFILIADO el valor que se encuentra en mora.todo caso, el monto a debitar/cargar de la cuenta bancaria o tarjeta de crédito del AFILIADO, no podrá exceder en un mes el valor equivalente a tres (3) Cuotas Mensuales de Afiliación
                Elite pactadas en este Contrato.</p>
        </td>
    </tr>
    <tr>
        <td>
            <p><b>CUARTO:</b>Es responsabilidad del AFILIADO, verificar que mensualmente se realice correctamente el débito automático de su cuenta bancaria y/o tarjeta de crédito</p>
        </td>
    </tr>
    <tr>
        <td>
            <p><b>QUINTO- DEBITO NO EXITOSO:</b>En el caso tal que el débito no pudiera ser efectuado, sea rechazado por el banco o suceda cualquier otra circunstancia que no permita su realización, BODYTECH o su árbitro podrá permitir el pago del concepto
                sujeto al débito automático en el Counter de la sede, previo el cobro administrativo que realice BODYTECH a modo de penalidad de acuerdo con las tarifas publicadas en la página Web de BODYTECH.</p><br>
        </td>
    </tr>
    <tr>
        <td><br>
            <p>El presente documento se firma el <?php echo $contract_date; ?></p><br>
        </td>
    </tr>
    <tr>
        <td><br>
            <p>Nombres y apellidos <?php echo $name; ?></p>
        </td>
    </tr>
    <tr>
        <td><br>
            <p>Documento: <?php echo $document_type; ?></p>
        </td>
    </tr>
    <tr>
        <td><br>
            <p>Numero: <?php echo $document_number; ?></p>
        </td>
    </tr>
    <tr>
        <td style="font-size: 10px;">
            <br><br><br>
            <?php echo $timestamp; ?>
        </td>
    </tr>
</table>