<table style=" position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
    <tr>
        <td>
            <p style=""><b> CLÁUSULA DE PERMANENCIA MÍNIMA Y COBRO DEL VALOR SUBSIDIADO POR TERMINACIÓN ANTICIPADA</b></p><br>
        </td>
    </tr>
</table>
<table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
    <tr>
        <td>
            <p>1. Objeto de la permanencia mínima - La presente permanencia mínima se pacta teniendo en cuenta que INVERSIONES EN RECREACIÓN DEPORTE Y SALUD S.A – BODYTECH otorgará una tarifa preferencial en cada categoría para aquellas personas que
                deseen tomar un plan con permanencia mínima de 12 meses según la siguiente tabla:</p> <br>
        </td>
    </tr>
</table>
<table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
    <tr>
        <td>
            <p><b> Cuadro comparativo de oferta al consumidor en las modalidades de contrato sin obligación de permanencia mínima y contratos con cláusula de permanencia mínima.</b></p>
        </td>
    </tr>
</table>

<table style="font-size:80%; border: 1px solid #000; border-collapse: collapse;  position: relative;width: 85%;height: 30px;margin: auto;text-align: justify; " >
    <tr>
        <th colspan="6" style="text-align: center;">Plan Elite</th>
    </tr>
    <tr class="title ">
        <td>Categoria</td>
        <td>Platino</td>
        <td>One</td>
        <td>Premium</td>
        <td>Classic</td>
        <td>Super</td>
    </tr>
    <tr>
        <td>Cuota mensualidad elite</td>
        <td>$ 250.000</td>
        <td>$ 185.000</td>
        <td>$ 149.000</td>
        <td>$ 115.000</td>
        <td>$ 99.900</td>
    </tr>
    <tr>
        <td>Derechos de acceso </td>
        <td>$ 500.000</td>
        <td>$ 370.000</td>
        <td>$ 299.800</td>
        <td>$ 230.000</td>
        <td>$ 199.800</td>
    </tr>
    <tr>
        <td>Una (1) sesión de SMC</td>
        <td>$ 70.000</td>
        <td>$ 70.000</td>
        <td>$ 70.000</td>
        <td>$ 70.000</td>
        <td>$ 70.000</td>
    </tr>
</table> <br>
<table style="font-size:80%;border: 1px solid #000; border-spacing: 5px; border-collapse: collapse; border-spacing: 5px; position: relative;width: 85%;height: 30px;margin: auto;text-align: justify; " border="1px">
    <tr>
        <th style="text-align: center;" colspan="6">Plan Elite Gold</th>
    </tr>
    <tr style="text-align: center;">
        <td>Categoria</td>
        <td>Platino</td>
        <td>One</td>
        <td>Premium</td>
        <td>Classic</td>
        <td>Super</td>
    </tr>
    <tr>
        <td>Cuota mensualidad elite </td>
        <td>$ 215.000</td>
        <td>$ 159.900</td>
        <td>$ 129.900</td>
        <td>$ 99.900</td>
        <td>$ 87.500</td>
    </tr>
    <tr>
        <td>Cuota mensualidad elite <br> Estudiante</td>
        <td>$ 175.000</td>
        <td>$ 129.500</td>
        <td>$ 104.930</td>
        <td>$ 80.500</td>
        <td>$ 69.930</td>
    </tr>
    <tr>
        <td>Derechos de acceso elite <br> estudiante</td>
        <td>$ 500.000</td>
        <td>$ 370.000</td>
        <td>$ 299.800</td>
        <td>$ 230.000</td>
        <td>$ 199.800</td>
    </tr>
    <tr>
        <td>Derechos de acceso elite</td>
        <td>$ 500.000</td>
        <td>$ 370.800</td>
        <td>$ 299.800</td>
        <td>$ 230.000</td>
        <td>$ 199.800</td>
    </tr>
    <tr>
        <td>Una (1) sesión de SMC</td>
        <td>Incluido</td>
        <td>Incluido</td>
        <td>Incluido</td>
        <td>Incluido</td>
        <td>Incluido</td>
    </tr>

</table><br>
<table cellpadding="1" cellspacing="1" style="font-size:70%;border:1px solid black;border-collapse: collapse; position: relative;width: 95%;height: 30px;margin: auto;text-align: justify; ">
    <tr>
        <th style="text-align: center;" colspan="13">Valor a pagar por retiro anticipado</th>
    </tr>
    <tr style="text-align: center;">
        <td>Categoria <br>/mes</td>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>5</td>
        <td>6</td>
        <td>7</td>
        <td>8</td>
        <td>8</td>
        <td>10</td>
        <td>11</td>
        <td>12</td>
    </tr>
    <tr>
        <td>Platino</td>
        <td>$ 516.000</td>
        <td>$ 473.000</td>
        <td>$ 430.000</td>
        <td>$ 387.000</td>
        <td>$ 344.000</td>
        <td>$ 301.000</td>
        <td>$ 258.000</td>
        <td>$ 215.000</td>
        <td>$ 172.000</td>
        <td>$ 129.000</td>
        <td>$ 86.000</td>
        <td>$ 43.000</td>
    </tr>
    <tr>
        <td>One</td>
        <td>$ 383.760</td>
        <td>$ 351.780</td>
        <td>$ 319.800</td>
        <td>$ 287.820</td>
        <td>$ 255.840</td>
        <td>$ 223.860</td>
        <td>$ 191.880</td>
        <td>$ 159.900</td>
        <td>$ 127.920</td>
        <td>$ 95.940</td>
        <td>$ 63.960</td>
        <td>$ 31.980</td>
    </tr>
    <tr>
        <td>Premium</td>
        <td>$ 311.760</td>
        <td>$ 285.780</td>
        <td>$ 259.800</td>
        <td>$ 233.820</td>
        <td>$ 207.840</td>
        <td>$ 181.860</td>
        <td>$ 155.880</td>
        <td>$ 129.900</td>
        <td>$ 103.920</td>
        <td>$ 77.940</td>
        <td>$ 51.960</td>
        <td>$ 25.980</td>
    </tr>
    <tr>
        <td>Classic</td>
        <td>$ 239.760</td>
        <td>$ 219.780</td>
        <td>$ 199.800</td>
        <td>$ 179.820</td>
        <td>$ 159.840</td>
        <td>$ 139.860</td>
        <td>$ 119.880</td>
        <td>$ 99.900</td>
        <td>$ 79.920</td>
        <td>$ 59.940</td>
        <td>$ 39.960</td>
        <td>$ 19.980</td>
    </tr>
    <tr>
        <td>Super</td>
        <td>$ 210.000</td>
        <td>$ 192.500</td>
        <td>$ 175.000</td>
        <td>$ 157.500</td>
        <td>$ 140.000</td>
        <td>$ 122.500</td>
        <td>$ 105.000</td>
        <td>$ 87.500</td>
        <td>$ 70.000</td>
        <td>$ 52.500</td>
        <td>$ 35.000</td>
        <td>$ 17.500</td>
    </tr>
</table><br>
<table style="font-size:70%;border: 1px solid #000; border-spacing: 5px; border-collapse: collapse; border-spacing: 5px; position: relative;width: 95%;height: 30px;margin: auto;text-align: justify; " border="1px">
    <tr>
        <th style="text-align: center;" colspan="13">Valor a pagar por retiro anticipado elite estudiante</th>
    </tr>
    <tr style="text-align: center;">
        <td>Categoria <br>/mes</td>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>5</td>
        <td>6</td>
        <td>7</td>
        <td>8</td>
        <td>8</td>
        <td>10</td>
        <td>11</td>
        <td>12</td>
    </tr>
    <tr>
        <td>Platino</td>
        <td>$ 420.000</td>
        <td>$ 385.000</td>
        <td>$ 350.000</td>
        <td>$ 315.000</td>
        <td>$ 280.000</td>
        <td>$ 245.000</td>
        <td>$ 210.000</td>
        <td>$ 175.000</td>
        <td>$ 140.000</td>
        <td>$ 105.000</td>
        <td>$ 70.000</td>
        <td>$ 35.000</td>
    </tr>
    <tr>
        <td>One</td>
        <td>$ 310.800</td>
        <td>$ 284.900</td>
        <td>$ 259.000</td>
        <td>$ 233.100</td>
        <td>$ 207.200</td>
        <td>$ 181.300</td>
        <td>$ 155.400</td>
        <td>$ 129.500</td>
        <td>$ 103.600</td>
        <td>$ 77.700</td>
        <td>$ 51.800</td>
        <td>$ 25.900</td>
    </tr>
    <tr>
        <td>Premium</td>
        <td>$ 251.832</td>
        <td>$ 230.846</td>
        <td>$ 209.860</td>
        <td>$ 188.874</td>
        <td>$ 167.888</td>
        <td>$ 146.902</td>
        <td>$ 125.916</td>
        <td>$ 104.930</td>
        <td>$ 83.944</td>
        <td>$ 62.958</td>
        <td>$ 41.972</td>
        <td>$ 20.986</td>
    </tr>
    <tr>
        <td>Classic</td>
        <td>$ 193.200</td>
        <td>$ 177.100</td>
        <td>$ 161.000</td>
        <td>$ 144.900</td>
        <td>$ 128.800</td>
        <td>$ 112.700</td>
        <td>$ 96.600</td>
        <td>$ 80.500</td>
        <td>$ 64.400</td>
        <td>$ 48.300</td>
        <td>$ 32.200</td>
        <td>$ 16.100</td>
    </tr>
    <tr>
        <td>Super</td>
        <td>$ 167.832</td>
        <td>$ 153.846</td>
        <td>$ 139.860</td>
        <td>$ 125.874</td>
        <td>$ 111.888</td>
        <td>$ 97.902</td>
        <td>$ 83.916</td>
        <td>$ 69.930</td>
        <td>$ 55.944</td>
        <td>$ 41.958</td>
        <td>$ 27.972</td>
        <td>$ 13.986</td>
    </tr>
</table><br>
<table style=" position: relative;width: 95%;height: 30px;margin: auto;text-align: justify; ">
    <tr>
        <td>
            <p>2. Duración de la permanencia mínima –El término de la permanencia mínima es de doce (12) meses contados a partir del momento en que se active la afiliación, entendida esta como el momento en el cual EL AFILIADO hace el pago efectivo de
                la misma.</p>
        </td>
    </tr>
</table><br>

<table style=" position: relative;width: 95%;height: 30px;margin: auto;text-align: justify; ">
    <tr>
        <td>
            <p>de la Afiliación y de la Inscripción al Plan Elite, tiempo durante el cual el AFILIADO podrá hacer uso del Club Médico Deportiv o BODYTECH de acuerdo a su categoría y tarifa. Si el AFILIADO no manifiesta su intención de dar por terminado
                el contrato de prestación de servicios una vez culmine el término de permanencia mínima, el contrato se entenderá prorrogado indefinidamente y el costo mensual de la afiliación se incrementará con base en el índice de Precios al Consumidor
                (IPC) más dos (2) puntos porcentuales .
            </p>
        </td>
    </tr>
</table><br>
<table style=" position: relative;width: 95%;height: 30px;margin: auto;text-align: justify; ">
    <tr>
        <td>
            <p>4. Cobro de la penalidad por terminación anticipada: Si durante el término de duración de la permanencia mí nima, EL AFILIADO, solicita a INVERSIONES EN RECREACIÓN DEPORTE Y SALUD S.A – BODYTECH la terminación anticipada, el PRESTADOR
                cobrará al AFILIADO los valores subsidiados durante el término que estuvo vigente el contrato. Esta comunicación deberá entregarse y radicarse en el Counter de cada una de las sedes . En caso de no pago por parte del afiliado de las
                sumas adeudas, BODYTECH procederá a reportar ante Data crédito el comportamiento moroso del afiliado conforme a la autorización otorgada en el contrato único de prestación de servicios.</p>
        </td>
    </tr>
</table><br>
<table style=" position: relative;width: 95%;height: 30px;margin: auto;text-align: justify; ">
    <tr>
        <td>
            <p>5. Estos cobros también aplican para el plan familiar con cláusula de permanencia mínima en los montos subsidiados por Bodytech</p>
        </td>
    </tr>
</table><br>
<table style=" position: relative;width: 95%;height: 30px;margin: auto;text-align: justify; ">
    <tr>
        <td>
            <p>6. Declaro que conozco y acepto el contenido de este documento y que todos los dato s aquí suministrados son reales y fidedignos.</p>
        </td>
    </tr>
</table><br>
<table width="100%" style=" position: relative;width: 95%;height: 30px;margin: auto;text-align: justify; ">
    <tr>
        <td width="50%">
            <p>Nombres y apellidos: <?php echo $name; ?></p>
            <p>Documento: <?php echo $document_type; ?> </p>
            <p>Número: <?php echo $document_number; ?> </p>
            <p style="font-weight: bold; margin-top: 60px; margin-right: 15px;"> Firma cuenta habiente: <?php echo $name; ?></p>
        </td>
        <td width="50%">
            <p>Nombres y apellidos: <?php echo $name; ?></p>
            <p>Documento: <?php echo $document_type; ?> </p>
            <p>Número: <?php echo $document_number; ?>  </p>
            <p style="font-weight: bold; margin-top: 60px;">Firma beneficiario: <?php echo $name; ?></p>
        </td>
    </tr>
    <tr>
        <td colspan="2" style="font-size: 10px;">
            <br><br><br>
            <?php echo $timestamp; ?>
        </td>
    </tr>
</table>