<table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
        <tr>
            <td>
                <p>
                    <b>1.&nbsp;&nbsp;&nbsp;<u>MORA EN LOS PAGOS PLANES ELITE Y CORPORATIVO:</u></b>
                </p><br>
            </td>
        </tr>

        <tr>
            <td>
                <p><b>Definición:</b> Entiéndase por mora aquella situación en la que EL AFILIADO Y/O BENEFICIARIO DEL CONVENIO NO se encuentra al día con sus pagos conforme a lo establecido en este contrato.EL AFILIADO Y/O BENEFICIARIO DEL CONVENIO que
                    se encuentre en mora no podrá ingresar a las sedes Bodytech, sin realizarse de forma previa una verificación por parte del counter de la sede sobre el estado de la mora en los pagos que presenta el AFILIADO.</p>
                <br>
            </td>
        </tr>

        <tr>
            <td>
                <p>
                    <b>Parágrafo 1:</b> El AFILIADO de plan elite cuyo débito automático no pueda ser efectuado, sea rechazado por el banco o suceda cualquier otra circunstancia que no permita su realización, BODYTECH o su árbitro podrá permitir el pago
                    del concepto sujeto al débito automático en el Counter de la sede, previo el cobro administrativo que realice BODYTECH a modo de penalidad de acuerdo con las siguientes tarifas: categorías Platino, One y Premium : $15.000; categorías
                    Classic, Súper y Zonal: $10.000. El PRESTADOR no repondrá́ el tiempo que estuvieron bloqueados los beneficiarios del convenio por concepto de mora.
                </p>
            </td>
        </tr>

        <tr>
            <td>
                <p>
                    <b>Parágrafo 2:</b> El afiliado del plan ELITE que se encuentre en mora no podrá́ solicitar congelaciones, cambios de categoría o plan, cesiones de contrato, retiros o cualquier otra prerrogativa que se otorgue al AFILIADO por el Club
                    Médico Deportivo BODYTECH hasta tanto no se cancelen los saldos adeudados.
                </p>
                <br>
            </td>
        </tr>

        <tr>
            <td>
                <p>
                    <b>2.&nbsp;&nbsp;&nbsp;<u>PROCEDIMIENTO PARA DÉBITO PLAN ELITE:</u></b>
                </p><br>
            </td>
        </tr>

        <tr>
            <td>
                <p>El valor de la cuota mensual de Afiliación se cobrará mensualmente con un primer débito bimestre anticipado y el segundo débito y subsiguientes meses anticipados. El débito a la cuenta bancaria o tarjeta de crédito por concepto de la Cuota
                    Mensual de Afiliación Elite, lo realizará la entidad financiera que el AFILIADO señale, y en caso de algún error en el valor debitado, el AFILIADO deberá informar conjunta y simultáneamente a la entidad financiera y a BODYTECH de esta
                    situación.
                </p>
            </td>
        </tr>

        <tr>
            <td>
                <p>
                    <b>Parágrafo:</b> Es responsabilidad del AFILIADO, verificar que mensualmente se realice correctamente el débito automático de su cuenta bancaria y/o tarjeta de crédito. En caso de existir algún inconveniente en el débito, el AFILIADO
                    podrá pagar su Cuota Mensual de Afiliación Elite en el Counter de la respectiva sede al Club Médico Deportivo BODYTECH.
                </p>
                <br>
            </td>
        </tr>

    </table>
    
    <table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
        <tr>
            <td>
                <p>
                    <b> 3.&nbsp;&nbsp;&nbsp;<u>OBLIGACIONES DEL AFILIADO:</u>
                        </b>
                </p><br>
            </td>
        </tr>
        
        <tr>
            <td>
                <p>
                    <b>a.</b> EL AFILIADO deberá cumplir en forma eficiente y oportuna las siguientes reglas: Es obligación del AFILIADO practicarse el exámen médico y/o exámen de aptitud física seleccionada (evaluación médica y/o clínica), exigida para
                    definir un programa médico deportivo adecuado. Una vez evaluado y con su programa de entrenamiento establecido por el Club Médico Deportivo BODYTECH, se obliga a seguir a cabalidad las indicaciones del programa de entrenamiento en
                    cuanto a repeticiones, tiempos y frecuencias de asistencia, de lo contrario, el prestador queda exonerado de responsabilidad alguna. <b>Parágrafo 1:</b> En el evento en que el AFILIADO decida no practicarse la evaluación médica y/o
                    clínica o decida no seguir el programa de entrenamiento elaborado por el PRESTADOR, deberá suscribir el documento de exoneración de responsabilidad en la sede del Club Médico Deportivo BODYTECH en la que realizará su entrenamiento,
                    previo al inicio de este. Parágrafo 2: Así mismo, quedará exonerado de responsabilidad el PRESTADOR, en caso de producirse un accidente por una indebida manipulación de los equipos por parte del AFILIADO.
                </p>
            </td>
        </tr>

        <tr>
            <td>
                <p>
                    <b>b.</b> Conocer y respetar los <b>TÉRMINOS Y CONDICIONES DE LA PRESTACIÓN DEL SERVICIO</b> expuestos en este documento, los reglamentos establecidos para las actividades específicas y seguir las indicaciones de los Médicos Deportólogos,
                    Fisioterapeutas, Nutricionistas, Evaluadores Clínicos, entrenadores, entrenadores de Clases Grupales y entrenador Personalizado del Club Médico Deportivo BODYTECH.
                </p>
            </td>
        </tr>

        <tr>
            <td>
                <p>
                    <b>c.</b> Pagar oportunamente el valor del Plan.
                </p>
            </td>
        </tr>

        <tr>
            <td>
                <p>
                    <b>d.</b> Mantenerse durante todo el tiempo de vigencia del Contrato afiliado a una EPS y/o MEDICINA PREPAGADA y tener al día los aportes al régimen de seguridad social en salud. Al inicio, y en cualquier momento durante la vigencia
                    del Contrato, el PRESTADOR podrá requerir los comprobantes que evidencien la afiliación del AFILIADO al sistema de seguridad social en salud y que los pagos se encuentren al día.
                </p>
            </td>
        </tr>

        <tr>
            <td>
                <p>
                    <b>e.</b> Suministrar y declarar información completa y veraz al Club Médico Deportivo BODYTECH y a todo el personal de Médicos Deportólogos, Fisioterapeutas, Nutricionistas, Evaluadores Clínicos, Entrenadores, Entrenadores de Clases
                    Grupales y Entrenador Personalizado sobre su estado de salud.
                </p>
            </td>
        </tr>

        <tr>
            <td>
                <p>
                    <b>f.</b> Conocer las condiciones de los servicios que prestan terceros diferentes al PRESTADOR en las instalaciones del Club Médico Deportivo BODYTECH. EL AFILIADO hará uso de estos servicios ofrecidos por terceros sólo si conoce
                    y acepta las condiciones de prestación de tales servicios. Se entenderá que existe aceptación tácita de las citadas condiciones de servicio con el mero uso de estos por parte del AFILIADO.
                </p>
            </td>
        </tr>

        <tr>
            <td>
                <p>
                    <b>g.</b> EL AFILIADO Y/O BENEFICIARIO DEL CONVENIO se obligan a preservar todos los elementos puestos a su disposición por parte del Club Médico Deportivo BODYTECH para realizar la actividad física, so pena de pagar el valor equivalente
                    a su reposición y/o arreglo.
                </p>
            </td>
        </tr>

    </table>
    
    <table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
        <tr>
            <td>
                <p>
                    <b>h.</b> EL AFILIADO,LA EMPRESA BENEFICIARIA DEL CONVENIO Y/O BENEFICIARIO DEL CONVENIO deberá presentar las Peticiones, Quejas y Reclamos según los parámetros establecidos en la ley y bajo el sistema establecido por el PRESTADOR,
                    cuya información se encuentra disponible en el documento anexo a este contrato y que hace parte integrante del mismo, el cual el AFILIADO declara conocer y aceptar.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>i.</b> EL AFILIADO del plan ELITE deberá cancelar la mensualidad bajo la modalidad de débito automático. En caso de no poderse realizar el débito, EL AFILIADO podrá cancelar en sede. Esto no podrá exceder tres (3) pagos consecutivos.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b><u> 4.   OBLIGACIONES Y DERECHOS DEL PRESTADOR: </u>
                        </b>
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>a.</b> Permitir el acceso del AFILIADO a las sedes del Club Médico Deportivo BODYTECH a las que tiene derecho conforme al PLAN y categoría adquiridos o a las sedes en operación al momento de la firma del contrato.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>b.</b> Mantener en forma adecuada sus instalaciones.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>c.</b> Ofrecer valoraciones médicas o clínicas AL AFILIADO, de acuerdo a las necesidades del afiliado y según el plan escogido. Las citas para la valoración médica o clínica inicial de ingreso, así como cualquier otro servicio que
                    lo requiera, están sujetas a previa coordinación entre el Club Médico Deportivo BODYTECH y el AFILIADO, teniendo en cuenta la disponibilidad de personal y las instalaciones.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>d.</b> El PRESTADOR manifiesta y así lo reconoce el AFILIADO, que el derecho de acceso al Club Médico Deportivo BODYTECH y acceso a la valoración médica de ingreso antes indicada equivale a un valor del (AÑO (34%), SEMESTRE ( 36%)
                    TRIMESTRE (52%) del valor que se pague en razón de este Contrato, suma que, una vez practicada la evaluación en ningún caso será reembolsable toda vez que la misma hace parte de los costos en que incurre EL PRESTADOR para poner a disposición
                    del AFILIADO los servicios correspondientes. No aplica para plan Elite.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b> e. </b> Modificar de acuerdo a la demanda de cada una de las sedes, los horarios y las categorías de estas, de las clases grupales de una o varias de sus sedes, al igual que reducir o aumentar el número de clases y designar o remover
                    libremente los entrenadores o al personal que labora en las sedes donde opera el Club Médico Deportivo BODYTECH y que prestan servicios al Afiliado. Las modificaciones realizadas sobre los horarios, cantidades y entrenadores de las
                    clases grupales serán comunicadas al afiliado en cada sede del Club Médico Deportivo BODYTECH donde ocurran los cambios o por cualquier otro medio que el PRESTADOR estime idóneo y efectivo para comunicar el hecho. <b> PARÁGRAFO
                        1:</b> En el caso de presentarse cambio de categoría de una de las sedes del Club Médico Deportivo BODYTECH, a una categoría superior, el AFILIADO que asista a la sede recategorizada automáticamente subirá de categoría. No obstante,
                    lo anterior, EL AFILIADO, LA EMPRESA BENEFICIARIA DEL CONVENIO Y/O BENEFICIARIO DEL CONVENIO al momento de la renovación asumirá el incremento del valor del plan de afiliación. <b> PARÁGRAFO 2: </b> Para el Plan Elite el incremento
                    aplica según lo establecido en los <b>TÉRMINOS  Y  CONDICIONES  DE  LA  PRESTACIÓN  DEL SERVICIO.</b>
                </p>
            </td>
        </tr>
    </table>
    
    <table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
        <tr>
            <td>
                <p>
                    <b>f. </b> Ampliar, reducir, remodelar o cerrar, temporal o definitivamente las sedes donde opera el Club Médico Deportivo BODYTECH cuando las condiciones del negocio así lo determinen. Cuando el cierre de la sede sea por un período
                    superior a un (1) mes, el afiliado podrá optar entre continuar disfrutando los servicios contratados en otra sede de igual o inferior categoría a las contratadas, o terminar unilateral y anticipadamente el contrato. En el evento en
                    el que el AFILIADO escoja la terminación del contrato, el PRESTADOR reembolsará a este valor correspondiente que hubiere pagado y no hubiere disfrutado y el valor de los costos no reembolsables desde el día en que el AFILIADO presente
                    la solicitud escrita de terminación en la respectiva del Club Médico Deportivo BODYTECH de acuerdo a su tarifa y categoría. Este pago lo realizará el PRESTADOR dentro de los treinta (30) días siguientes a la fecha en que el AFILIADO
                    realice la notificación de cancelación.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b><u>5.DEVOLUCIONES:</u>
                        </b> No hay lugar a devoluciones por ningún concepto con excepción del caso contemplado en el literal 6 aparte OBLIGACIONES Y DERECHOS DEL PRESTADOR, caso en el cual se devolverá el dinero en proporción
                    al tiempo pagado y que falte por ser utilizado en tal momento.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b><u>6. CAMBIO DE PLAN Y/O CATEGORÍA:</u>
                        </b> Se entenderá como cambio de plan y/o categoría, cuando el AFILIADO solicite cambio de una categoría y/o plan baja a una más alta y viceversa.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b> a.</b> En caso de que el AFILIADO solicite un cambio de categoría y su factura no haya superado los 30 días después de generada, se liquidará la diferencia con las tarifas existentes en el momento de solicitar el cambio. Para todos
                    los efectos se tendrá como fecha de inicio del plan la estipulada antes del cambio de categoría.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>b.</b> En caso de que el AFILIADO solicite un cambio de categoría y su factura sea superior al día 30 después de generada, se tendrá en cuenta el saldo a favor del tiempo restante de su plan de afiliación y se calculará la diferencia
                    sobre tarifa vigente sin promoción. <b>PARÁGRAFO 1:</b> Para el plan Elite se debe cancelar el valor diferencial entre la cuota de inscripción y el pago por derecho de acceso a servicios médicos deportivos y evaluaciones médicas. El
                    pago mensual se actualizará a la nueva categoría y/o plan solicitado.<b> PARÁGRAFO 2:</b> Para el plan estándar, el cambio de categoría se generará al momento de la solicitud y se deberá cancelar el valor diferencial entre el pago
                    por derecho de acceso a servicios médicos deportivos y evaluaciones médicas entre la categoría actual y la nueva categoría. En el plan estándar no podrá realizar Down grade (cambio de categoría hacia una más baja) Para el plan corporativo
                    aplica según tarifas del convenio.
                </p>
                <br>
            </td>
        </tr>
    </table>
    
    <table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
        <tr>
            <td>
                <p>
                    <b><u>7.   TERMINACIÓN: </u>
                        </b>
                </p>
                <br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <u><b>POR PARTE DEL PRESTADOR:</b>
                        </u>
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>
                         a.
                        </b> EL PRESTADOR podrá dar por terminado este contrato en cualquier tiempo de manera unilateral y sin la devolución de sumas de dinero, por el incumplimiento del AFILIADO de las obligaciones derivadas en el
                    contrato y en los <b>TÉRMINOS Y CONDICIONES DE LA PRESTACIÓN DEL SERVICIO</b> expuestos en este documento. La terminación no generará indemnización alguna a favor del afiliado.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>b.
                        </b>EL PRESTADOR podrá dar por terminado este contrato en cualquier tiempo de manera unilateral y sin la devolución de sumas de dinero, por el incumplimiento del AFILIADO de las obligaciones derivadas en el
                    contrato y en los TÉRMINOS Y CONDICIONES DE LA PRESTACIÓN DEL SERVICIO expuestos en este documento. La terminación no generará indemnización alguna a favor del afiliado.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>c.
                        </b>EL AFILIADO, que atente contra las buenas costumbres y/o sana convivencia al interior de cualquier Club Médico Deportivo BODYTECH, que se exprese de forma indebida hacia los demás AFILIADOS y/o empleados
                    del PRESTADOR, y que promocione bienes y servicios utilizando las sedes de <b> EL PRESTADOR </b>sin autorización escrita de <b> EL  PRESTADOR</b>, será automáticamente desafiliado y perderá inmediatamente el valor pagado por la cuota
                    de Inscripción.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b><u>POR PARTE DEL AFILIADO</u>
                        </b>
                </p>
                <br>
            </td>
        </tr>
        <tr>
            <td>
                <p>A solicitud de EL AFILIADO, siempre y cuando EL AFILIADO, LA EMPRESA BENEFICIARIA DEL CONVENIO Y/O BENEFICIARIO DEL CONVENIO se encuentren al día en los pagos. <b> <u><br> PARAGRAFO 1:</u></b> Sin perjuicio de la terminación del contrato,
                    el PRESTADOR podrá cobrar los saldos adeudados por el AFILIADO vía cobro jurídico y mediante el reporte a las centrales de riesgo. El PRESTADOR podrá hacer efectivo el débito automático directamente y/o delegar y/o autorizar a la persona
                    o entidad que considere pertinente e idónea para cumplir la función de recaudo de las sumas adeudadas por el AFILIADO. <br><b>  <u> PARAGRAFO 2:</u></b> El AFILIADO plan Elite, podrá terminar unilateralmente el presente Contrato previa
                    notificación radicada por escrito al PRESTADOR con no menos de treinta (30) días calendario de anticipación a la fecha de terminación efectiva. El PRESTADOR facturará al AFILIADO los treinta (30) días que surte el trámite de cancelación
                    de la Afiliación y de la Inscripción al Plan Elite, tiempo durante el cual el AFILIADO podrá hacer uso del Club Médico Deportivo BODYTECH de acuerdo a su categoría y tarifa. <br><b> <u> PARAGRAFO 3:</u></b> EL AFILIADO que haya aceptado
                    expresamente y en documento aparte un período de permanencia mínima se atendrá a lo pactado en dicho documento respecto a la solicitud de cancelación del servicio.
                </p><br>
            </td>
        </tr>
    </table>
    
    <table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
        <tr>
            <td>
                <p>
                    <b>  <u>8.   CESIÓN DEL CONTRATO:</u>
                        </b>EL AFILIADO podrá transferir las obligaciones y derechos que surgen del presente contrato y que no se hayan utilizado, en los siguientes casos:
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>a.</b> Por muerte del AFILIADO. En este evento, dentro de los sesenta (60) días siguientes al fallecimiento, el (los) heredero(s) o causahabiente(s) deberá(n) radicar en la sede del Club Médico Deportivo BODYTECH, una comunicación
                    escrita solicitando la cesión del Contrato por el tiempo del plan que no haya sido disfrutado por el difunto e indicando la fecha a partir de la cual se activará dicha cesión. A dicha comunicación deberá adjuntar: <b> (a)</b> fotocopia
                    del documento de identidad del cesionario,<b> (b) </b> Registro Civil de Defunción del AFILIADO. <b> (c)</b> Declaración extra-proceso ante notario público, que haga referencia a la calidad de (compañero(a), hermano(a), hijo(a), padre/madre
                    o familiar) del cesionario con el AFILIADO, y <b> (d)</b> declaración extra-proceso ante notario público que indique que el cesionario es el único beneficiario del AFILIADO y no existe persona alguna con mejor derecho.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>b.</b> Por incapacidad médica del AFILIADO conforme a las reglas descritas en la cláusula décima tercera de este documento.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>c.</b> Por solicitud escrita del AFILIADO siempre y cuando se encuentre a paz y salvo en el cumplimiento de la totalidad de sus obligaciones y medie aceptación expresa por parte del PRESTADOR del servicio. La cesión deberá solicitarse
                    por escrito mediante carta entregada en la ciudad donde se efectuó la afiliación y con una antelación mínima de ocho (8) días calendario a la fecha efectiva. La cesión o transferencia aplica desde la fecha de radicada la solicitud,
                    no retroactivamente Si la persona que recibe el plan nunca ha sido afiliada a Bodytech deberá cancelar el valor del derecho de acceso a servicios médicos deportivos y evaluaciones médicas, y si el plan que va a recibir es de mayor
                    categoría, deberá cancelar la diferencia del derecho de acceso. <br><b> PARAGRAFO 1:</b> EL AFILIADO que adquiera un PLAN anual o semestral, tendrá derecho a realizar una transferencia sin cobro alguno. En caso de presentarse una segunda
                    transferencia en el citado plan, el AFILIADO realizará un pago adicional dependiendo de la categoría. EL AFILIADO, LA EMPRESA BENEFICIARIA DEL CONVENIO Y/O BENEFICIARIO DEL CONVENIO que adquiera un PLAN Trimestral, mes a mes y/o más
                    de una cesión del plan, deberá realizar un pago adicional dependiendo de la categoría.<br> <b>PARAGRAFO 2 - Plan Elite:</b> Para el plan elite no aplican la cesión (transferencia) del contrato.<br> <b>PARAGRAFO 3 – Plan corporativo:</b> Las
                    transferencias de planes corporativos sólo deben hacerse a personas que trabajen en la misma EMPRESA BENEFICIARIA DEL CONVENIO con carta de autorización de ésta. Si la empresa no es quien paga podrá transferirse únicamente a los familiares
                    en primer grado de consanguinidad y/o afinidad (papá, mamá, hermanos, hijos,cónyuge) El AFILIADO deberá enviar una carta solicitando la transferencia con los datos de la persona BENEFICIARIA y copia de los documentos de identidad.
                    La solicitud deberá enviarse al correo electrónico  <a href="">servicioalcliente@bodytechcorp.com.</a>  Si es para un tercero, este debe asumir el pago de los derechos de acceso a servicios médicos deportivos y evaluaciones médicas,
                    además la diferencia del plan a recibir a tarifa oficial <br><b> PARAGRAFO 4:</b> EL AFILIADO, LA EMPRESA BENEFICIARIA DEL CONVENIO Y/O BENEFICIARIO DEL CONVENIO que realice ingresos por medio de tiqueteras, no podrá cederlas toda vez
                    estas son personales e intransferibles, con vigencia de dos meses a partir de su compra.<br> <b> PARAGRAFO 5:</b> Quien sea beneficiario de la Cesión del Plan de afiliación deberá suscribir un nuevo contrato de prestación de servicios
                    y demás documentos exigidos por el PRESTADOR.
                </p><br>
            </td>
        </tr>
    </table>
    
    <table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
        <tr>
            <td>
                <p>
                    <b><u>9. SUSPENSIÓN  PROVISIONAL DE SERVICIOS POR  INCAPACIDAD Y/O CONGELACIÓN.:</u></b>
                </p><br>
            </td>
        </tr>

        <tr>
            <td>
                <b>a.
                        <u>CONGELACIÓN  PLAN  ESTÁNDAR:
                        </u>
                    </b>EL AFILIADO que adquiera un PLAN anual, tendrá́ derecho a congelar, sin costo alguno, el servicio dos (2) veces durante la vigencia de su PLAN. Él término de cada congelación, no podrá́ ser inferior a 7 días, ni
                superior a (30) treinta días. EL AFILIADO que adquiera un PLAN semestral, tendrá́ derecho a congelar el servicio por una (1) sola vez sin costo alguno. Él término de la(s) congelación no podrá́ ser inferior a (7) siete días ni superior
                a (30) treinta días. EL AFILIADO que adquiera un PLAN Trimestral o inferior solo podrá́ congelar la prestación del servicio pagando el valor establecido por cada día de suspensión siempre y cuando el plan se encuentre activo. Él término
                de suspensión en ningún caso podrá́ ser inferior a (7) siete días. EL AFILIADO que adquiera un PLAN mes a mes, no tendrá́derecho a congelar su contrato.
            </td>
        </tr>
        <tr>
            <td>
                <p><b>b.
                           <u>CONGELACIÓN PLAN ELITE:</u>
                         </b>EL AFILIADO del plan ELITE, podrá́ suspender (congelar) temporalmente su plan de afiliación por un periodo mínimo de (7) siete días y hasta (30) treinta días calendario. Durante el tiempo congelado, El AFILIADO pagará el 25%
                    del valor de cada uno de los días congelados por concepto de mantenimiento de sede, equipos y mantenimiento de inscripción. Los días del mes que no se encuentren dentro de las fechas de congelación, serán pagados al 100% de la cuota
                    mensual de su afiliación al Plan Elite.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b><u>PARÁGRAFO 1:</u>
                        </b>En los planes ELITE ANTICIPADO (ANT) EL AFILIADO tendrá derecho a dos congelaciones de mínimo siete (7) días y hasta (30) treinta días sin costo. El beneficio de las dos congelaciones se entregará una vez
                    al año contadas a partir de la fecha de su afiliación y éstas no son acumulables año a año.
                </p> <br>
            </td>
        </tr>
    </table>
    
    <table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
        <tr>
            <td>
                <p>
                    <b>
                          CONDICIONES:
                        </b> Toda congelación deberá́ solicitarse por parte del AFILIADO el mes anterior a la fecha efectiva de esta. EL AFILIADO no podrá́ ingresar a la sede durante el tiempo congelado. En caso de que EL AFILIADO
                    desista de la congelación, para ser reactivado, pagará el cien por ciento (100%) de los días restantes del mes que pretende disfrutar. Al momento de solicitar la congelación el afiliado no puede encontrarse en mora. Las solicitudes
                    de congelación aplicarán únicamente para períodos que no se encuentren pagados por el afiliado.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b><u>PARÁGRAFO 2:</u></b>La congelación de los servicios deberá́ solicitarse a través de la página web <a href="https://bodytech.com.co/perfil/novedades/"> https://bodytech.com.co/perfil/novedades/</a> o comunicarse a través de la
                    línea de servicio al cliente 7422639 en Bogotá, línea gratuita nacional 018000182639. Dicho plan debe encontrarse activo al momento de la solicitud y no puede estar en mora.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b><u>PARÁGRAFO 3:</u>
                        </b>Las congelaciones no aplican de forma retroactiva.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b><u>PARÁGRAFO 4:</u>
                        </b>LOS AFILIADOS a BODYTECH a través de un PLAN ELITE GRUPAL O FAMILIAR, deben radicar tanto las congelaciones como los retiros de forma “INDIVIDUAL” porque independientemente de la persona a la que se le realiza
                    el débito, se trata de contratos de afiliación distintos, con derechos y obligaciones que se predican respecto de cada afiliado no respecto del grupo o familia asociados a la persona que se le realiza el débito de su tarjeta crédito,
                    cuenta ahorros o cuenta corriente.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b> c. INCAPACIDAD:</b>Incapacidades médicas: La incapacidad médica del AFILIADO para usar los servicios del Club Médico Deportivo BODYTECH, suspende el contrato y no tendrá cobro alguno, siempre y cuando ésta sea certificada por el
                    médico de la E.P.S. a la cual esté vinculado EL AFILIADO y sea verificada por el médico Deportólogo de una de las sedes del Club Médico Deportivo BODYTECH. La incapacidad médica deberá ser presentada dentro de los treinta (30) días
                    siguientes al cumplimiento de la incapacidad. Durante el tiempo reportado de incapacidad, no debe presentar ingresos, excepto en los casos en que tenga activo un servicio médico complementario. Parágrafo 1: Para el plan Elite se aplicará
                    como un saldo a favor hacia futuro por el período establecido en la incapacidad, siempre y cuando el débito haya sido efectivo.
                </p><br>
            </td>
        </tr>
    </table>
    
    <table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
        <tr>
            <td>
                <p><b><u>10. DECLARACIONES DEL AFILIADO: </u></b></p>
            </td>
        </tr>
        <tr>
            <td>
                <p>El AFILIADO para efectos de celebrar el presente Contrato declara, manifiesta y acepta lo siguiente:</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>a.</b>Que una de las políticas BODYTECH es el mejoramiento continuo a fin de prestar todos los días un mejor servicio a sus afiliados. Por esta razón el AFILIADO entiende y acepta que pueden ocurrir incomodidades o limitaciones
                    de algunos servicios contratados, con ocasión de obras de remodelación o refacción que el PRESTADOR vaya a realizar en algunos de los Clubs Médicos Deportivos BODYTECH. Estas situaciones serán informadas a todos los afiliados con una
                    anterioridad debida en cada sede del Club Médico Deportivo BODYTECH, o a través la página web www.bodytech.com.co, o de la línea de atención al cliente BODYTECH: (+1) 7422639.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>b.</b> Que conoce, entiende y acepta que los servicios ofrecidos y prestados por terceros independientes, autónomos y diferentes al PRESTADOR en las instalaciones donde operan los Club s Médicos Deportivos BODYTECH, son ofrecidos
                    y prestados de manera independiente por un tercero diferente del PRESTADOR y por lo tanto, el PRESTADOR no es responsable por cualquier garantía, daño o perjuicio que se derive o pueda derivarse de dichos ofrecimientos, venta de productos
                    o prestación de servicios.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b><u>11. DOMICILIO  CONTRACTUAL  Y  NOTIFICACIONES  JUDICIALES: </u>
                        </b> Para todos los efectos judiciales, se conviene como lugar de cumplimiento de las obligaciones derivadas del presente contrato la ciudad donde se suscribe el contrato. Las Partes acuerdan que las notificaciones
                    judiciales que se les deba realizar, en razón de este Contrato, se remitirán únicamente por escrito a las siguientes direcciones: EL PRESTADOR: BODYTECH Carrera 20 No. 83-20 Piso 8, Bogotá, D.C. o AFILIADO (previamente identificado
                    en el acápite “información personal “de este contrato).
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b><u>12. MODIFICACIONES.</u>
                        </b>El PRESTADOR podrá modificar de acuerdo a las necesidades del servicio los TÉRMINOS Y CONDICIONES DE LA PRESTACIÓN DEL SERVICIOexpuestos en este documento. De realizarse alguna modificación, esta será informada
                    de manera oportuna y por medios idóneos y eficaces al AFILIADO.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b><u>13. PRESTACION  DE  SERVICIOS  ADICIONALES.</u>
                        </b>La suscripción de este contrato no otorga al AFILIADO el derecho a exigir la prestación de Servicios Médicos Complementarios. Para que el AFILIADO pueda acceder a estos servicios deberá pagar los valores
                    adicionales que correspondan por este concepto, de acuerdo a las tarifas vigentes establecidas por el PRESTADOR de acuerdo a la categoría de cada sede del Club Médico Deportivo BODYTECH, y las cuales pueden ser consultadas por el AFILIADO
                    en el Counter de ingreso y con los Asesores comerciales o integrales.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b><u>14. SOLICITUDES,  TRÁMITES  Y  NOVEDADES.</u>
                        </b>Todas las solicitudes, trámites y/o novedades que el AFILIADO tenga en cuanto a la prestación de los servicios aquí contratados serán atendidas por el PRESTADOR en cualquiera de sus sedes o en su línea de
                    servicio al cliente: Línea Nacional 018000182639, Bogotá 0317422639 o al correo electrónico <a href="servicioalcliente@bodytechcorp.com"> servicioalcliente@bodytechcorp.com</a>. PARÁGRAFO: Las solicitudes o requerimientos que realice
                    el AFILIADO por algún canal o medio distinto a los señalados en este aparte se entenderá como no efectuada.
                </p>
            </td>
        </tr>
    </table>
    
    <table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
        <tr>
            <td>
                <p>
                    <b><u>15. INVITADOS:</u>
                        </b>Cualquier AFILIADO podrá invitar por una (1) sola vez a una (1) persona que deberá reunir las siguientes condiciones: (i) no estar afiliada, (ii) que su estado de afiliación sea inactivo como mínimo en los
                    últimos seis (6) meses, (iii) que no tenga deudas pendientes con el Club Médico Deportivo BODYTECH, y (iv) que no haya disfrutado ninguna otra cortesía en ese período. Con la autorización previa del Gerente de la respectiva sede del
                    Club Médico Deportivo BODYTECH, un AFILIADO podrá invitar hasta tres (3) personas en forma simultánea. Los invitados deberán presentar documento de identidad, firmar el Contrato de Invitado, llenar el documento de Clasificación de
                    población, atender las indicaciones del instructor durante su práctica y respetar las normas y reglamentos del Club Médico Deportivo BODYTECH. El Club Médico Deportivo BODYTECH se reserva el derecho de admisión de aquellos invitados
                    cuya presentación o condiciones personales al momento de solicitar el ingreso no estén acordes con la imagen pública del Club Médico Deportivo BODYTECH, tales como el uso de jean u otra clase de pantalón no apto para la realización
                    de la práctica deportiva, así como zapatos no apropiados. Las políticas de admisión de Invitados están sujetas a cambios, sin previo aviso.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b><u>16. PRESENTACIÓN   PERSONAL:</u>
                        </b>Podrán ingresar a las instalaciones aquellos AFILIADOS cuya presentación personal se considere apropiada conforme la imagen pública del Club Médico Deportivo BODYTECH, sus normas o regulaciones. Los ejercicios
                    se deben practicar con el atuendo adecuado a la actividad que se esté realizando. Cada AFILIADO deberá traer para su comodidad una toalla cuyo uso es obligatorio durante y después de cada ejercicio. Está prohibido quitarse la ropa
                    y/o circular por el Club Médico Deportivo BODYTECH en traje de baño y/o sin camiseta. El único sitio dispuesto para que los AFILIADOS o Invitados se cambien de ropa en las sedes del Club Médico Deportivo BODYTECH es el vestier y el
                    baño. No se permitirá la utilización de lenguaje soez ni atuendos con propaganda política o comercial de cualquier índole en las sedes del Club Médico Deportivo BODYTECH. Una vez concluida la práctica de cualquier ejercicio o rutina,
                    se deberán dejar los correspondientes implementos (mancuernas, discos, pesas, barras, colchonetas, etc.) en su lugar. Para garantizar la comodidad de todos y como demostración de cortesía, todo AFILIADO deberá limpiar las máquinas
                    e implementos que utilice una vez finalizado el ejercicio, para esto el Club Médico Deportivo BODYTECH ha dispuesto en sus sedes de paños de tela y líquidos desinfectantes. En cualquier lugar del Club Médico Deportivo BODYTECH está
                    prohibido el consumo de cigarrillos, bebidas alcohólicas, el uso de esteroides y/o drogas nocivas para la salud o ilícitas, como también la práctica de toda actividad bajo sus efectos. Para el ingreso a la zona húmeda (turco y sauna),
                    el atuendo debe ser vestido de baño y/o pantaloneta licrada, toalla y sandalias de caucho antideslizante. El AFILIADO debe hacer uso de la ducha antes de ingresar a esta zona, y está prohibido afeitarse o usar cremas o exfoliantes
                    en ella.
                </p>
            </td>
        </tr>
    </table>
    
    <table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
        <tr>
            <td>
                <p>
                    <b><u>17. LOCKERS:</u>
                        </b>Se hace claridad que BODYTECH NO presta el servicio de custodia de bienes por tener a disposición de los clientes unos LOCKERS. Estos espacios son simplemente una prerrogativa que da BODYTECH y por ende,
                    esta prerrogativa NO hace parte del Contrato de Prestación de Servicios Médicos Deportivos suscrito con los clientes. En caso que el cliente o AFILIADO desee bajo su propia responsabilidad utilizar los lockers, tendrá la obligación
                    de colocar en el locker a utilizar durante todo el tiempo que tome su entrenamiento, un candado de su propiedad que sea fuerte y seguro. Se PROHIBE guardar en los lockers artículos de valor o documentos personales. El Club Médico Deportivo
                    BODYTECH no asume ninguna custodia o deber de conservación frente a los bienes dejados en los lockers CON o SIN candado o que correspondan a relojes, billeteras, documentos personales, tarjetas débito o crédito, audífonos de cualquier
                    tipo, llaves de vehículos, joyas, dinero en efectivo o celulares, los cuales expresamente está PROHIBIDO dejar en los casilleros por seguridad, por ello, la compañía no asume ninguna responsabilidad por ningún bien en caso de pérdida
                    o robo. Todos los días al finalizar la jornada, se abrirán los lockers de la sede, y los artículos allí encontrados se considerarán abandonados y serán relacionados en la bitácora de objetos encontrados en sede. Si aparece el propietario,
                    este deberá entregar información suficiente que garantice su propiedad sobre el artículo, y este será entregado por el personal de la sede, previa firma por parte del propietario en la bitácora. Los artículos que sean abandonados en
                    los lockers serán guardados por un período de un (1) mes. Pasado este término se donarán a alguna entidad de beneficencia. El Club Médico Deportivo BODYTECH no acepta ninguna responsabilidad por los artículos abandonados en los lockers..
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b><u>18. UTILIZACIÓN DE EQUIPOS E INSTALACIONES:</u>
                        </b>Con el propósito de garantizar que todos los AFILIADOS reciban un tratamiento equitativo, sólo podrán utilizarse los equipos durante el tiempo indicado en el programa médico deportivo y establecido para
                    cada persona. Además, su uso deberá efectuarse en la forma autorizada por el Club Médico Deportivo BODYTECH de acuerdo con su naturaleza y de acuerdo con las indicaciones del fabricante. Para este fin deberán atenderse estrictamente
                    las instrucciones y las carteleras correspondientes. Los AFILIADOS no están autorizados para vender dentro de las instalaciones ningún bien o servicio, ni para prestar servicios de entrenamiento personalizado, ni para mover o modificar
                    los equipos en forma alguna. Las pesas y demás piezas sueltas de equipos solo podrán ser utilizadas en las áreas destinadas para tal efecto y de acuerdo a las condiciones establecidas para su uso. Si algún AFILIADO considera que uno
                    de los equipos está funcionando de forma deficiente, deberá informar esta situación al Gerente de la respectiva sede, a fin de que sean tomadas las medidas de rigor. Así mismo, está prohibido el uso de teléfonos celulares y otros dispositivos
                    electrónicos durante el uso de los equipos de entrenamiento. No se permite que los AFILIADOS y/o sus invitados utilicen sus propios equipos en las instalaciones del Club Medico Deportivo. El Club Médico Deportivo BODYTECH no permite
                    utilizar ningún equipo de entrenamiento físico si el AFILIADO está tomando cualquier medicamento que cause mareo, vértigo o somnolencia, o si
                </p>
            </td>
        </tr>
    </table>
    
    <table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
        <tr>
            <td>
                <p>este sufre una condición médica contraindicada. El AFILIADO asume total responsabilidad por las lesiones físicas o accidentes ocurridos como resultado de la práctica de los ejercicios o actividades que tienen lugar en las instalaciones
                    del Club Médico Deportivo BODYTECH, a menos que se trate de entrenamiento personalizado y EL AFILIADO atienda las instrucciones del instructor o a algún desperfecto de los equipos de entrenamiento. Para su bienestar y mejores resultados,
                    el AFILIADO deberá seguir todas las indicaciones del Médico Deportólogo, de los Fisioterapeutas y Entrenadores. Si el AFILIADO desea utilizar un plan de entrenamiento físico distinto al diseñado para él por el Club Médico Deportivo
                    BODYTECH, debe firmar el documento de Exoneración de Responsabilidad, so pena de no poder utilizar o continuar utilizando las instalaciones del Club Médico Deportivo.
                </p><br>
            </td>
        </tr>

        <tr>
            <td>
                <p>
                    <b><u>19. PROHIBICIONES:</u>
                        </b>El AFILIADO entiende y conoce que todos los colaboradores del Club Médico Deportivo BODYTECH, tienen PROHIBIDO, la realización de las siguientes actividades:
                </p>
            </td>
        </tr>

        <tr>
            <td>
                <p>
                    <b>a.</b> Vender o comercializar a los AFILIADOS a título personal, productos (bebidas energizantes o de cualquier tipo, complementos alimenticios, vitamínicos, calóricos, medicinas, anabólicos, ropa, accesorios deportivos entre otros)
                    o servicios (entrenamiento personalizado o semi-personalizado dentro o fuera de las instalaciones de cada sede distintos a los ofrecidos o comercializados por el PRESTADOR en la sede del Club Médico Deportivo BODYTECH de acuerdo a
                    la categoría de esta.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>b.</b> El AFILIADO que no acate y cumpla el presente reglamento, no podrá reclamar directa o indirectamente ante BODYTECH por las garantías, consecuencias, perjuicios o daños que estos productos o servicios comercializados de manera
                    fraudulenta le pudiesen llegar a ocasionar.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>c.</b> El incumplimiento de este reglamento genera a favor del Club Médico Deportivo BODYTECH el derecho de terminación unilateral del contrato sobre el AFILIADO.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>d.</b> Tan pronto el AFILIADO tenga conocimiento de algún hecho como los antes descritos, o que sea similar o análogo, o que le genere sospecha, deberá informar y poner en conocimiento de esta situación al PRESTADOR mediante documento
                    escrito, el cual podrá radicar en la sede del Club Médico Deportivo BODYTECH de acuerdo a su categoría o tarifa, o a los correos electrónicos: <u style="color:darkblue;"> servicioalcliente@bodytechcorp.com</u> o <u style="color: darkblue;"> planelite@bodytechcorp.com.</u>
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b> 20.<u>PARQUEADEROS:</u>
                        </b>El PRESTADOR de manera expresa manifiesta que los servicios contratados por el AFILIADO no incluyen el servicio de parqueadero en ninguna de las categorías, tarifas y/o sedes del Club Médico Deportivo BODYTECH.
                    Podrá haber
                </p>
            </td>
        </tr>
    </table>
    
    <table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
        <tr>
            <td>
                <p>algunas sedes del Club Médico Deportivo BODYTECH que mediante convenios con terceros brinden este beneficio para comodidad del AFILIADO; Sin embargo, el AFILIADO recibirá este servicio bajo las condiciones y términos de prestación del
                    servicio que establezcan tales terceros, condiciones las cuales se obliga el AFILIADO a consultar y conocer previamente. No es obligación de BODYTECH prestar el servicio de parqueadero en ninguna sede El AFILIADO reconoce y acepta
                    que cuando haga uso de estos parqueaderos, el único responsable por la integridad de su vehículo y lo que hay en su interior, es el administrador del parqueadero.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>21.<u>HORARIOS DE OPERACIÓN:</u>
                        </b>Los horarios de operación de cada una de las sedes a nivel nacional o su categoría, pueden ser consultados por los AFILIADOS directamente en el Counter de la respectiva sede, o a través de la página de internet
                    <a href="https://bodytech.com.co/"> www.bodytech.com.co</a>.
                </p><br>
            </td>
        </tr>

        <tr>
            <td>
                <p>
                    <b> 22. <u>COMIDAS Y BEBIDAS:</u>
                        </b>Los alimentos sólo podrán ser consumidos en las áreas destinadas específicamente por cada sede para tal fin. En ningún caso se permitirá su consumo en los vistieres, las zonas húmedas o zonas de ejercicios.
                    Agradecemos la correcta y debida utilización de los recipientes de basura instalados para cada tipo de desecho.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>23. <u>MENORES DE EDAD:</u>
                        </b>Todos los menores de dieciocho (18) años y mayores de trece (13) años podrán afiliarse al Club Médico Deportivo BODYTECH, para ello sus padres y/o representantes autorizados deben suscribir el respectivo
                    contrato único de servicios, la copia de este Reglamento y firmar el formato de Consentimiento Informado, que se comprometen a respetar. Para la utilización de las instalaciones y equipos, el menor de edad deberá asistir a la evaluación
                    médica previamente. Los menores de trece (13) años sólo podrán ingresar a aquellas sedes en la cuales existan áreas específicamente destinadas para su uso; en la demás no podrán ser admitidos por razones de seguridad, salvo en los
                    casos particulares donde la compañía lo autorice.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>24. <u>RECUPERACIÓN DE TIEMPO POR INASISTENCIA DEL AFILIADO:</u>
                        </b>El Club Médico Deportivo BODYTECH no se hace responsable por recuperación de tiempo de afiliación por inasistencia del AFILIADO, después de que éste haya iniciado su PLAN. No obstante, lo anterior, se exceptúan
                    las modalidades de congelación y/o incapacidad descritas en el contrato único de servicios.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b> 25. <u>BENEFICIOS ADICIONALES DE LOS AFILIADOS AL CLUB MÉDICO DEPORTIVO BODYTECH: </u>
                        </b>
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>a.</b> Tarifa preferencial en el acceso a Servicios Médicos Complementarios.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>b.</b>EL AFILIADO podrá utilizar hasta por un término no mayor a treinta (30) días calendario contados desde el primer día de acceso, los servicios de los establecimientos del Club médico deportivo BODYTECH ubicados en otros países,
                    siempre y cuando dichos Clubs pertenezcan a la categoría contratada por el cliente o inferior, sin que sea necesario efectuar pagos adicionales a
                </p>
            </td>
        </tr>
    </table>
    
    <table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
        <tr>
            <td>
                <p>los establecidos en este contrato. Los establecimientos a los cuales puede acceder EL AFILIADO en otros países podrán ser consultados en <a href="http://www.bodytech.com.co"> http://www.bodytech.com.co.</a> En caso de que EL AFILIADO,
                    LA EMPRESA BENEFICIARIA DEL CONVENIO Y/O BENEFICIARIO DEL CONVENIO desee seguir haciendo uso de los servicios en el establecimiento fuera del país por más de los treinta (30) días, deberán proceder con el pago de la correspondiente
                    afiliación. </p> <br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b> 26. <u>CONDICIONES PRESTACIÓN DEL SERVICIO ENTRENAMIENTO PERSONALIZADO, PILATES REFORMER Y MMA.</u>
                        </b>
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>Los servicios descritos en esta cláusula se ofrecen y se prestan de forma mensual con una frecuencia semanal determinada por el paquete adquirido por EL AFILIADO. La frecuencia de la prestación del servicio de entrenamiento personalizado,
                    pilates reformer y MMA puede ser de una, dos, tres o cuatro veces por semana. La mensualidad de entrenamiento personalizado, pilates reformer y MMA tiene una vigencia de treinta (30) días contados a partir de la fecha de inicio del
                    servicio; una vez cumplido este término de vigencia, no habrá lugar a devoluciones o compensaciones de sesiones. Las clases tendrán una duración máxima de sesenta (60) minutos, de los cuales los últimos cinco (5) minutos se utilizarán
                    para trámites administrativos (firma de la hoja de asistencia por parte del afiliado). En caso de llegar el afiliado después de la hora programada para tomar su clase de entrenamiento personalizado, pilates reformer o MMA, dicho tiempo
                    será descontado del término de duración de la sesión. Las sesiones de entrenamiento personalizado, pilates reformer y artes marciales mixtas (MMA) deberán programarse de mutuo acuerdo con el profesor asignado con no menos de 12 horas
                    de anticipación, de acuerdo a la disponibilidad del profesor. En caso de no poder asistir a la sesión agendada, El afiliado deberá solicitar su cancelación con una antelación de 12 horas, so pena de perder la sesión. El Afiliado deberá
                    atender todas las recomendaciones que le haga el profesional del ejercicio o profesional de la salud, de lo contrario, el prestador queda exonerado de responsabilidad. Las tarifas de los servicios aquí descritos dependen de la categoría
                    de la sede.</p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>27. <u>CONDICIONES PRESTACIÓN DEL SERVICIO NUTRICIÓN</u><br><br><br>
                        </b> Las sesiones de servicio de nutrición se deben agendar en el counter de la sede o a través de servicio al cliente según disponibilidad del profesional y de los horarios. El día de la sesión el Afiliado
                    deberá llevar ropa deportiva y no debe haber entrenado 3 horas antes de la valoración. Las sesiones tendrán una vigencia de dos (2) meses contadas a partir de la fecha de compra. Si el afiliado no agenda las sesiones dentro del término
                    de la vigencia las perderá. En caso de no poder asistir a la sesión agendada, El afiliado deberá solicitar su cancelación con una antelación de 24 horas, so pena de perder la sesión.
                </p><br>
            </td>
        </tr>
    </table>
    
    <table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
        <tr>
            <td>
                <p>
                    <b>28.<u>CONDICIONES PRESTACIÓN DEL SERVICIO ELITE + NUTRICIÓN – PSICOLOGIA</u>
                        </b>
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>El servicio de nutrición y Piscología ofrecido en este Plan se prestará al afiliado vía telefónica, chat y/o video chat. El horario para la prestación del servicio de nutrición será de lunes a viernes de 9:am a 7:pm, sábados de 9:am a
                    12 del día y para el de Psicología 7x24 los 365 días del año. Este servicio de asistencia se presta por Psicólogos especializados y se presta en áreas como: trastornos alimenticios, manejo de estrés, inquietudes personales (depresión,
                    inseguridades, fobias, soledad, sentimientos de autoestima, estrés psicosocial, imagen Corporal, confianza personal, sexualidad, Adicciones, Anorexia, bulimia, síndrome de Abstinencia, Egocentrismo, fatiga etc. El servicio de nutrición
                    y psicología virtual no está sujeto a congelaciones, cambios de categoría e incapacidades. El retiro de este servicio está sujeto a la cancelación del plan elite. El afiliado que se encuentre en mora no se le permitirá el ingreso ni
                    prestará el servicio hasta que realice el pago de los saldos adeudados. En caso que el cliente desee enviar alguna solicitud, Queja o Reclamo respecto a los servicios recibidos, los puede hacer llamando a la línea 4864901 o al correo
                    Electrónico Nutrición Objetivos <a style="color: darkblue;">nutricion.objetivos@bodytechcorp.com</a>.Para activar el servicio el afiliado después de la compra deberá llamar a cualquiera de las siguientes Líneas de atención: Línea de
                    Atención: 031486 4901-3222575097 en Bogotá.</p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>29. <u>CONDICIONES DE USO SERVICIO DE PISCINA:</u>
                        </b>El AFILIADO deberá hacer uso obligatorio de: gorro y vestido de baño en material apropiado, utilizar el vestier, cumplir con las buenas prácticas sanitarias. Se prohíbe: el ingreso a menores de doce (12)
                    años sin el acompañamiento de un adulto responsable, el uso de la piscina a personas con heridas visibles, laceraciones o infecciones en la piel, el ingreso a la piscina en estado de embriaguez o bajo el efecto de sustancias psicoactivas,
                    el consumo de alimentos, bebidas o fumar en la zona de piscina así como el ingreso de botellas de vidrio, el ingreso a los usuarios que porten cadenas, collares, camisetas o elementos similares que permitan el atrapamiento mecánico,
                    así como el uso de cremas, cosméticos o aceites de cualquier tipo, la práctica de actividades de contacto dentro y fuera de la piscina, tales como clavados, carreras y juegos violentos.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>30.<u>CONDICIONES DE USO SERVICIO DE ELITE + PISCINA:</u>
                        </b>
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>El servicio de elite + piscina se puede congelar a solicitud del afiliado o por cuestiones de salud presentando la respectiva excusa médica. El retiro de este servicio está sujeto a la cancelación del plan elite. El plan elite adquirido
                    no está sujeto a cambios de categoría. El afiliado que se encuentre en mora no se le permitirá el ingreso ni prestará el servicio hasta que realice el pago de los saldos adeudados Las sesiones del plan de piscina están sujetas a una
                    evaluación para determinar el nivel. De acuerdo con los resultados de la evaluación siempre y cuando se apruebe el exámen, el Afiliado podrá tomar práctica libre, dentro de los 30 días del mes en los horarios y términos de uso fijados
                    por Bodytech Active, en caso contrario, El afiliado podrá tomar hasta 4 sesiones de piscina dentro de los 30 días del mes incluidas en su plan en las cuales se le </p>
            </td>
        </tr>
    </table>
    
    <table style="position: relative;width: 95%;height: 30px;margin: auto;text-align: justify;">
        <tr>
            <td>
                <p>enseñarán los fundamentos de los diferentes estilos de natación. Las 4 sesiones por mes incluidas en el plan no son acumulables para los meses siguientes. Todas las sesiones se deben agendar de forma previa con mínimo tres (3) horas de
                    anticipación siempre y cuando haya cupo. La cancelación de la sesión deberá hacerse con mínimo tres (3) horas de antelación. La no asistencia a la sesión agendada y reservada sin previa cancelación será registrada como sesión realizada.
                    El afiliado deberá presentarse ante el profesor que le dará la clase con diez (10) minutos de anticipación. El afiliado deberá asistir con chanclas, traje de baño, toalla, gafas y gorro. Está prohibido el ingreso al agua con ropa interior.
                    El afiliado deberá firmar el libro de asistencia antes de iniciar la sesión. Se debe Comunicar, informar y abstenerse de asistir a las sesiones o práctica libre en cualquier caso de enfermedad viral (diarrea, vómito, fiebre) o laceración.
                    No consumir alimentos 1 hora antes y lácteos 3 horas antes a la realización de las sesiones o práctica libre. Dar información veraz sobre los datos solicitados. Seguir las indicaciones del personal de la institución. Para las sesiones
                    de natación, solo puede ingresar un (1) acompañante / acudiente con los niños menores de edad. Los afiliados disfrutarán de una comunicación clara con el entrenador respecto al entrenamiento y actividades que desarrollan, dando soluciones
                    a dudas e inquietudes.</p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>31. <u>NORMAS ADICIONALES:</u>
                        </b>El Club Médico Deportivo BODYTECH. Se reserva el derecho de modificar, adicionar o complementar estas normas y regulaciones en cualquier momento a su discreción. Todas las modificaciones, adiciones y demás,
                    entrarán en vigor inmediatamente. El desacato o violación de estas dará lugar a la cancelación de los derechos del AFILIADO, como también en los casos en que su comportamiento sea considerado molesto, perturbador, inmoral o fraudulento.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>El Club Médico Deportivo BODYTECH no se hace responsable por los contratos, acuerdos o convenios realizados por los AFILIADOS con cualquiera de las concesiones u subarrendatarios ubicados en las diferentes sedes (Terceros independientes)
                    tales como: Clubes de Estética, Cafetería, Almacén, Peluquería, Cámaras de Bronceo, Spa ´s y otros. Por esta razón, antes de contratar los servicios ofrecidos por los TERCEROS, el USUARIO debe haber conocido y aceptado los términos
                    y condiciones de los citados servicios por ellos ofrecidos. El Club Médico Deportivo BODYTECH tampoco se hace responsable por los acuerdos realizados por EL AFILIADO con el personal de BODYTECH a modo personal.
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <b>32. <u>CAMBIO DE FECHA DE INICIO</u>
                        </b>
                </p><br>
            </td>
        </tr>
        <tr>
            <td>
                <p>En el plan estándar, EL AFILIADO, LA EMPRESA BENEFICIARIA DEL CONVENIO Y/O BENEFICIARIO DEL CONVENIO pueden solicitar que se haga un cambio de fecha de inicio por una sola vez, hasta dentro de los tres (3) meses siguientes a la fecha en
                    que suscriba este documento, siempre y cuando EL AFILIADO, LA EMPRESA BENEFICIARIA DEL CONVENIO Y/O BENEFICIARIO DEL CONVENIO cumplan con los términos y condiciones de la prestación del servicio, paguen la totalidad del PLAN, no presente ingresos y no se haya superado la fecha de inicio del débito (en el caso del plan Elite).Parágrafo 1: En los planes corporativos, la duración
                    del contrato estará supeditada a la realización de los pagos por parte de la empresa beneficiaria del convenio y/o beneficiario del convenio. La iniciación del plan de afiliación se contará a partir de su activación en el sistema del
                    Club Médico Deportivo BODYTECH.</p>
            </td>
        </tr>
        <tr>
        <td style="font-size: 10px;">
            <br><br><br>
            <?php echo $timestamp; ?>
        </td>
    </tr>
    </table>
    