version: '3'

services:
  app:
    container_name: appAuth
    build: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - '4000:80'
    expose:
      - '4000'
    # depends_on:
    #   - mysql
    # links:
    #   - mysql

  # mysql:
  #   container_name: mysql
  #   image: mysql:8
  #   environment:
  #     MYSQL_DATABASE: root
  #     MYSQL_ROOT_PASSWORD: Bogota2015
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   ports:
  #     - '3307:3307'
