<table align="center" width="690px">
    <tr>
        <td>               
             <img style="border-radius: 8px;" width="690px" src="https://bodytech-correo.s3-us-west-2.amazonaws.com/plan.jpg"><br><br><br>
        </td> 
    </tr>

    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">
            <h1 style="font-size: 36px;line-height: 2px;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;"><b>GRACIAS!</b></h1>
            <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 16px;line-height: 20px;color: #3C3C3B;">
                HAZ TOMADO LA MEJOR DESICIÓN PARA TU CUERPO
            </p>
            <hr style="border-top: .2px solid #ccc;margin-bottom: 30px;margin-top: 38px;">
        </td>
    </tr>

    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">    
            <p style="font-size: 13px;line-height: 20px;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;">INFORMACIÓN DE COMPRA</p>
            <hr style="border-top: .2px solid #ccc;margin-bottom: 30px;margin-top: 38px;">   
        </td>
    </tr>

    <tr>    
        <td style="padding-left: 35px; padding-right: 35px;">
            <p style="font-size: 15px;line-height: 90%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;">
                <b>
                    <?php echo $plans_data[0]['contracted_plan'];?> <?php $duracion;?> SEDE <?php echo $venue;?>
                </b>
            </p>
            <?php if($is_elite){?>
                <p style="text-align: justify;font-size: 16px;line-height: 20px;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;">Afiliación por 12 meses en categoría <?php echo $category;?> con débito automático mensual. La suscripción se renovará automáticamente cada año hasta que se cancele.</p>
            <?php }else{?>
                <p style="text-align: justify;font-size: 16px;line-height: 20px;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;"><?php echo $description_plan;?></p>
            <?php }?>
            <hr style="border-top: .2px solid #ccc;margin-bottom: 30px;margin-top: 38px;">
        </td>
    </tr>

    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">
            <table align="center" width="100%">
                <tr>
                    <td colspan="2" align="center" style="font-size: 15px;line-height: 90%;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;"><b><h2>Precio</h2></b></td> 
                </tr>
                
                <?php $sum = 0; foreach($buy_detail as $detail){ $sum = $sum + (float)$detail['value']; ?>
                    <tr>
                        <td style="font-size: 16px;line-height: 20px;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;"><?php echo $detail['description'];?></td>
                        <td  style="text-align: right; font-size: 16px;line-height: 20%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;<?php echo ($detail['value'] < 0)?"color:red":""; ?>">$ <?php echo $detail['value'];?></td>
                    </tr>
                <?php }?>

                <tr>
                    <td style="font-size: 16px;line-height: 20%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;"><b>TOTAL:</b></td>
                    <td style="text-align: right;font-size: 16px;line-height: 40px;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;"><b>$ <?php echo number_format($sum, 0, '', '.');?></b></td>
                </tr>

            </table><br> <br><br>
            
        </td>
    </tr>

    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">
            <p style="text-align: justify;font-size: 16px;line-height: 40px;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;">Posteriormente la tarifa mensual full segundo débito en adelante $ <?php echo number_format($plans_data[0]['plan_price'], 0, '', '.');?> <br>Tu plan vence el <b><?php echo $end_date;?></b></p> <br>
        </td>
    </tr>

    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">
            <p style="font-size: 16px;line-height: 90%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;"><b>MÉTODO DE PAGO</b></p>
            <p style="font-size: 16px;line-height: 20px;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;"><?php echo $franchise;?> finalizado en <br> <b><?php echo $card_number;?> <br><?php echo $name; ?></b></p> <br><br>
        </td>
    </tr>

    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">
            <p style="text-align: justify;font-size: 16px;line-height: 20px;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;">Siempre estamos aquí para ayudar. Si tienes alguna pregunta, visita nuestro Centro de Ayuda para obtener más información.
             <br> Adjunto encontrarás tu contrato con BODYTECH en PDF, la contraseña es tu número de documento.</p>
            <br><br>
            </td>
    </tr>

    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">
            <p style="text-align: center;font-size: 16px;line-height: 90%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;"><b>AHORA YA PUEDES COMENZAR TU ENTRENAMIENTO</b></p>
        </td>
    </tr>

    <!-- <tr>
        <td align="center" style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;">
            <a href="https://bodytech.com.co/perfil" target="_blank"  style="background-color: #DD702B;border: none;color: white;padding: 15px 32px;text-align: center;text-decoration: none;display: inline-block;font-size: 16px;border-radius: 6px;width: 250px;margin-bottom: 66px;margin-top: 16px;"><b>DESCARGAR CONTRATO</b></a>
        </td>
    </tr> -->

    <tr>
        <td style="background-color: #dfdfdb; border-radius: 8px;"> 
            <table cellpadding="0" cellspacing="0" width="87%" align="center">
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" width="80%" align="center"  height="90">
                            <tr>
                                <td width="50%" style="text-align: right;">
                                    <a href="https://bodytech.com.co/" target="_black" style="text-decoration: none;"><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/thumbnail_logo_BW.png" style="width: 99px;"></a>
                                </td>
                                <td width="50%" style="text-align: left;">
                                    <a href="https://bodytech.com.co/" target="_black" style="color: black; text-decoration: none;">.com.co</a> 
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" width="70%" align="center" height="50">
                            <tr>
                                <td><a href="https://bodytech.com.co/planes/en-sede" target="_blank" style="color: black;text-decoration: none;">PRECIOS</a></td>
                                <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                <td><a href="https://bodytech.com.co/sedes" target="_blank" style="color: black;text-decoration: none;">SEDES</a></td>
                                <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                <td><a href="https://bodytech.com.co/doctor-bodytech" target="_blank" style="color: black;text-decoration: none;">DR. BODYTECH</a></td>
                                <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                <td><a href="https://bodytech.com.co/contacto" target="_blank" style="color: black;text-decoration: none;">CONTACTO</a></td>
                            </tr>
                        </table>
                    </td>
                </tr>                    
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" width="25%" align="center"  height="90">
                            <tr>
                                <td><a href="https://www.facebook.com/clubbodytech" target="_blank"><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/thumbnail_ico_fb.png"></a></td>
                                <td><a href="https://www.instagram.com/ClubBODYTECH/" target="_blank" ><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/thumbnail_ico_ig.png"></a></td>
                                <td><a href="https://twitter.com/ClubBODYTECH" target="_blank"><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/thumbnail_ico_tw.png"></a></td>
                                <td><a href="https://www.youtube.com/channel/UCcBV2tUbfK8Esy5QjvraupQ" target="_blank"><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/thumbnail_ico_yt.png"></a></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 11px;line-height: 23px;color: #3C3C3B;text-align: justify;">© 2021 BODYTECH es una marca registrada de BODYTECH Corp en Colombia y Perú. Todos los derechos reservados.</p>
                        <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 11px;line-height: 23px;color: #3C3C3B;text-align: justify;"></p>
                        <p></p>
                        <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 11px;line-height: 23px;color: #3C3C3B;text-align: justify;">Si necesitas ayuda o tienes alguna pregunta, ponte en contacto con el Servicio de atención al cliente de Bodytech: en Bogotá: <a style="color:#D58C0B" ;>742 26 39</a>, Línea nacional <a style="color:#D58C0B" ;>01 8000 182 639</a> o WhatsApp <a style="color:#D58C0B" ;>322 800 0000 </a><br>Este mensaje es de caracter informativo<br><br> </p>
                        <p></p>
                    </td>
                </tr>
            </table>

        </td>
    </tr>
</table>