<table cellpadding="0" cellspacing="0" class="t-body" align="center" width="600">
    <tr>
        <td>
            <img style="border-radius: 8px;" width="690px" src="<?php echo $data_template->banner; ?>"><br><br><br>
        </td>
    </tr>
    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">
            <h1 style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-size: 36px;line-height: 35px;color: <?php echo $data_template->colour_text; ?>;margin-top: 30px;">BIENVENIDO!</h1>
        </td>
    </tr>
    <tr>
        <td style="padding-left: 35px; padding-right: 35px">
            <h1 style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 20px;line-height: 94px;color: <?php echo $data_template->colour_text; ?>;">ERES PARTE DEL CLUB</h1>
        </td>
    </tr>
    <tr>
        <td style="padding-left: 35px; padding-right: 35px">
            <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 21px;line-height: 26px;text-align: left;color: <?php echo $data_template->colour_text; ?>; ">Ahora tienes acceso a la plataforma de <?php echo $data_template->name_company; ?>. Compra tus planes, mira tu estado de cuenta, ingresa a la App y aprovecha todos los beneficios que te trae <?php echo $data_template->name_company; ?>.</p><br>
            <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 21px;line-height: 16px;text-align: left;color: <?php echo $data_template->colour_text; ?>;"> INFORMACIÓN DE TU CUENTA</p>
            <hr style="border-top: .2px solid #ccc;margin-bottom: 30px;margin-top: 38px;">
        </td>
    </tr>
    <tr>
        <td style="padding-left: 35px; padding-right: 35px">
            <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 21px;text-align: left;color: <?php echo $data_template->colour_text; ?>;">
                Tu usuario <br>
                <b><?php echo $email; ?></b>
            </p>
            <br>
        </td>
    </tr>
    <tr>
        <td style="padding-left: 35px;padding-right: 35px;padding-bottom: 40px;">
            <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;ont-style: normal;font-weight: normal;font-size: 17px;color: <?php echo $data_template->colour_text; ?>;text-align: center;">
                <a href="<?php echo $data_template->url; ?>" target="_blank"  style="background-color: <?php echo $data_template->button_profile->background_color; ?>;border: none;color: <?php echo $data_template->button_profile->colour_text; ?>;padding: 15px 32px;text-align: center;text-decoration: none;display: inline-block;font-size: 16px;border-radius: 6px;width: 250px;margin-bottom: 20px;margin-top: 5px;"><b>IR A MI PERFIL</b></a>
            </p>
        </td>
    </tr>
    <tr>
    <td style="background-color: <?php echo $data_template->footer->background_color; ?>; border-radius: 8px;"> 
            <table cellpadding="0" cellspacing="0" width="87%" align="center">
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" width="80%" align="center"  height="90">
                            <tr>
                                <td width="50%" style="text-align: right;">
                                    <a href="<?php echo $data_template->footer->url; ?>" target="_black" style="text-decoration: none;"><img src="<?php echo $data_template->footer->logo; ?>" style="width: 99px;"></a>
                                </td>
                                <td width="50%" style="text-align: left;">
                                    <a href="<?php echo $data_template->footer->url; ?>" target="_black" style="color: black; text-decoration: none;"><?php echo $data_template->footer->domain; ?></a> 
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" width="70%" align="center" height="50">
                            <tr>
                                <?php foreach($data_template->footer->menu as $value){ ?>
                                    <td><a href="<?php echo $value->link; ?>" target="_blank" style="color: black;text-decoration: none;"><?php echo $value->name; ?></a></td>
                                    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                <?php } ?>
                                
                            </tr>
                        </table>
                    </td>
                </tr>                    
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" width="25%" align="center"  height="90">
                            <tr>
                                <?php foreach($data_template->footer->social_networks as $value){ ?>
                                    <td><a href="<?php echo $value->link; ?>" target="_blank"><img src="<?php echo $value->img; ?>"></a></td>
                                <?php } ?>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 11px;line-height: 23px;color: <?php echo $data_template->colour_text; ?>;text-align: justify;"><?php echo $data_template->footer->text_1; ?></p>
                        <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 11px;line-height: 23px;color: <?php echo $data_template->colour_text; ?>;text-align: justify;"></p>
                        <p></p>
                        <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 11px;line-height: 23px;color: <?php echo $data_template->colour_text; ?>;text-align: justify;"><?php echo $data_template->footer->text_2; ?><a style="color:<?php echo $data_template->footer->phone->colour; ?>" ;><?php echo $data_template->footer->phone->local; ?></a>, Línea nacional <a style="color:<?php echo $data_template->footer->phone->colour; ?>" ;><?php echo $data_template->footer->phone->national; ?></a> o WhatsApp <a style="color:<?php echo $data_template->footer->phone->colour; ?>" ;><?php echo $data_template->footer->phone->whatsApp; ?> </a><br>Este mensaje es de caracter informativo<br><br> </p>
                        <p></p>
                    </td>
                </tr>
            </table>

        </td>
    </tr>
</table>