<table align="center" width="690px">
    <tr>
        <td>               
             <img style="border-radius: 8px;" width="690px" src="https://bodytech-correo.s3-us-west-2.amazonaws.com/plan.jpg"><br><br><br>
        </td> 
    </tr>

    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">
            <h1 style="font-size: 35px;line-height: 2px;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 14px;"><b>SOLICITUD DE NOVEDAD</b></h1>
        </td>
    </tr>

    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">    
            <p style="font-size: 17px;line-height: 20px;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 1px;"><?php echo $name;?></p>
        </td>
    </tr>

    <tr>    
        <td style="padding-left: 35px; padding-right: 35px;">
            <p style="font-size: 18px;line-height: 140%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 30px;margin-bottom: 70px;">Referente a la solicitud de novedad, damos respuesta de tu caso.</p>
        </td>
    </tr>
    <tr style=" border-radius: 8px;">
        <td style=" padding-left: 35px; padding-right: 35px;">

            <table align="center" width="100%" style="background-color: #dfdfdb; border-radius: 8px;">
                <tr><td><br></td></tr>
                <tr>
                    <td>
                        <table align="center" width="90%"height="90%" style="background-color: #dfdfdb; border-radius: 8px;" >
                            <tr>
                                <td width="55%" align="center" style=" text-align: left; font-size: 15px;line-height: 90%;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;">
                                    
                                        <h3><b> Nº De solicitud: </b><?php echo $request_id;?></h3>
                                </td> 
                                <td width="40%" align="center" style="text-align: left; font-size: 15px;line-height: 90%;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;">
                                    <b><h3>Fecha de solicitud</h3></b></td> 
                                <td width="5%" align="center" style="font-size: 15px;line-height: 90%;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;">
                                    <b><h3>Días</h3></b>
                                </td> 
                            </tr>
                            <tr>
                                <td style="font-size: 16px;line-height: 20px;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;"><b>Congelación</b> <?php echo $reason_message;?></td>
                                <td  style="font-size: 16px;line-height: 20%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;"><?php echo $start_date;?> - <?php echo $end_date;?></td>
                                <td  style="text-align: center; font-size: 16px;line-height: 20%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;"><?php echo $days;?></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr><td><br></td></tr>
            </table><br> <br><br>
        </td>
    </tr>

    <tr>    
        <td style="padding-left: 35px; padding-right: 35px;">
            <p style="font-size: 18px;line-height: 140%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 50px;margin-bottom: 10px;">En base al estudio realizado, te informamos que tu solicitud de congelación de plan, ha sido rechazada.</p>
        </td>
    </tr>

    <tr>    
        <td style="padding-left: 35px; padding-right: 35px;">
            <p style="font-size: 18px;line-height: 140%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 10px;margin-bottom: 100px;">La respuesta a tu solicitud, será notificada por medio de correo electrónico, y en tu cuenta <b>BodyTech</b></p>
        </td>
    </tr>

    <tr>
        <td align="center" style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;">
            <a href="https://bodytech.com.co/perfil" target="_blank"  style="background-color: #DD702B;border: none;color: white;padding: 15px 32px;text-align: center;text-decoration: none;display: inline-block;font-size: 16px;border-radius: 6px;width: 250px;margin-bottom: 66px;margin-top: 16px;"><b>IR A MI CUENTA</b></a>
        </td>
    </tr>

    <tr>
        <td style="background-color: #dfdfdb; border-radius: 8px;"> 
            <table cellpadding="0" cellspacing="0" width="87%" align="center">
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" width="80%" align="center"  height="90">
                            <tr>
                                <td width="50%" style="text-align: right;">
                                    <a href="https://bodytech.com.co/" target="_black" style="text-decoration: none;"><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/thumbnail_logo_BW.png" style="width: 99px;"></a>
                                </td>
                                <td width="50%" style="text-align: left;">
                                    <a href="https://bodytech.com.co/" target="_black" style="color: black; text-decoration: none;">.com.co</a> 
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" width="70%" align="center" height="50">
                            <tr>
                                <td><a href="https://bodytech.com.co/planes/en-sede" target="_blank" style="color: black;text-decoration: none;">PRECIOS</a></td>
                                <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                <td><a href="https://bodytech.com.co/sedes" target="_blank" style="color: black;text-decoration: none;">SEDES</a></td>
                                <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                <td><a href="https://bodytech.com.co/doctor-bodytech" target="_blank" style="color: black;text-decoration: none;">DR. BODYTECH</a></td>
                                <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                <td><a href="https://bodytech.com.co/contacto" target="_blank" style="color: black;text-decoration: none;">CONTACTO</a></td>
                            </tr>
                        </table>
                    </td>
                </tr>                    
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" width="25%" align="center"  height="90">
                            <tr>
                                <td><a href="https://www.facebook.com/clubbodytech" target="_blank"><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/thumbnail_ico_fb.png"></a></td>
                                <td><a href="https://www.instagram.com/ClubBODYTECH/" target="_blank" ><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/thumbnail_ico_ig.png"></a></td>
                                <td><a href="https://twitter.com/ClubBODYTECH" target="_blank"><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/thumbnail_ico_tw.png"></a></td>
                                <td><a href="https://www.youtube.com/channel/UCcBV2tUbfK8Esy5QjvraupQ" target="_blank"><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/thumbnail_ico_yt.png"></a></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 11px;line-height: 23px;color: #3C3C3B;text-align: justify;">© 2021 BODYTECH es una marca registrada de BODYTECH Corp en Colombia y Perú. Todos los derechos reservados.</p>
                        <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 11px;line-height: 23px;color: #3C3C3B;text-align: justify;"></p>
                        <p></p>
                        <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 11px;line-height: 23px;color: #3C3C3B;text-align: justify;">Si necesitas ayuda o tienes alguna pregunta, ponte en contacto con el Servicio de atención al cliente de Bodytech: en Bogotá: <a style="color:#D58C0B" ;>742 26 39</a>, Línea nacional <a style="color:#D58C0B" ;>01 8000 182 639</a> o WhatsApp <a style="color:#D58C0B" ;>322 800 0000 </a><br>Este mensaje es de caracter informativo<br><br> </p>
                        <p></p>
                    </td>
                </tr>
            </table>

        </td>
    </tr>
</table>