<table align="center" width="690px">
    <tr>
        <td>               
             <img style="border-radius: 8px;" width="690px" src="<?php echo $data_template->banner; ?>"><br><br><br>
        </td> 
    </tr>

    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">
            <h1 style="font-size: 38px;line-height: 2px;color: <?php echo $data_template->colour_text; ?>;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;"><b>TU CONTRASEÑA</b></h1>
            <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 18px;line-height: 20px;color: <?php echo $data_template->colour_text; ?>;">
                ¿OLVIDASTE TU CONTRASEÑA? A TODOS NOS PASA
            </p><br><br>
        </td>
    </tr>

    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">    
            <p style="font-size: 18px;line-height: 20px;color: <?php echo $data_template->colour_text; ?>;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;">Si es así, confirma la solicitud. Este enlace es temporal, caduca en 24 horas. <br>
                Si no tienes intención de restablecer tu contraseña, ignora este email.</p> <br>
        </td>
    </tr>
    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">    
            <p style="font-size: 18px;line-height: 20px;color: <?php echo $data_template->colour_text; ?>;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;">No olvides que tu email de registro es:</p>
        </td>
    </tr>

    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">
            <p style="text-align: justify;font-size: 17px;line-height: 90%;color: <?php echo $data_template->colour_text; ?>;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 4px;"><b><?php echo $email; ?></b></p> <br>
        </td>
    </tr>


    <tr>
        <td align="center" style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;">
            <a href="<?php echo $data_template->url.$token_reset; ?>" target="_blank"  style="background-color: <?php echo $data_template->button_reset->background_color; ?>; border: none;color: <?php echo $data_template->button_reset->colour_text; ?>;padding: 15px 32px;text-align: center;text-decoration: none;display: inline-block;font-size: 16px;border-radius: 6px;width: 250px;margin-bottom: 66px;margin-top: 16px;"><b>RESTABLECER</b></a>
        </td>
    </tr>

    <tr>
        <td style="background-color: <?php echo $data_template->footer->background_color; ?>; border-radius: 8px;"> 
            <table cellpadding="0" cellspacing="0" width="87%" align="center">
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" width="80%" align="center"  height="90">
                            <tr>
                                <td width="50%" style="text-align: right;">
                                    <a href="<?php echo $data_template->footer->url; ?>" target="_black" style="text-decoration: none;"><img src="<?php echo $data_template->footer->logo; ?>" style="width: 99px;"></a>
                                </td>
                                <td width="50%" style="text-align: left;">
                                    <a href="<?php echo $data_template->footer->url; ?>" target="_black" style="color: black; text-decoration: none;"><?php echo $data_template->footer->domain; ?></a> 
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" width="70%" align="center" height="50">
                            <tr>
                                <?php foreach($data_template->footer->menu as $value){ ?>
                                    <td><a href="<?php echo $value->link; ?>" target="_blank" style="color: black;text-decoration: none;"><?php echo $value->name; ?></a></td>
                                    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                <?php } ?>
                                
                            </tr>
                        </table>
                    </td>
                </tr>                    
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" width="25%" align="center"  height="90">
                            <tr>
                                <?php foreach($data_template->footer->social_networks as $value){ ?>
                                    <td><a href="<?php echo $value->link; ?>" target="_blank"><img src="<?php echo $value->img; ?>"></a></td>
                                <?php } ?>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 11px;line-height: 23px;color: <?php echo $data_template->colour_text; ?>;text-align: justify;"><?php echo $data_template->footer->text_1; ?></p>
                        <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 11px;line-height: 23px;color: <?php echo $data_template->colour_text; ?>;text-align: justify;"></p>
                        <p></p>
                        <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 11px;line-height: 23px;color: <?php echo $data_template->colour_text; ?>;text-align: justify;"><?php echo $data_template->footer->text_2; ?><a style="color:<?php echo $data_template->footer->phone->colour; ?>" ;><?php echo $data_template->footer->phone->local; ?></a>, Línea nacional <a style="color:<?php echo $data_template->footer->phone->colour; ?>" ;><?php echo $data_template->footer->phone->national; ?></a> o WhatsApp <a style="color:<?php echo $data_template->footer->phone->colour; ?>" ;><?php echo $data_template->footer->phone->whatsApp; ?> </a><br>Este mensaje es de caracter informativo<br><br> </p>
                        <p></p>
                    </td>
                </tr>
            </table>

        </td>
    </tr>
</table>