<table align="center" width="690px">
    <tr>
        <td>               
             <img style="border-radius: 8px;" width="690px" src="https://bodytech-correo.s3-us-west-2.amazonaws.com/plan.jpg"><br><br><br>
        </td> 
    </tr>

    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">
            <h1 style="font-size: 38px;line-height: 2px;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 14px;"><b>RESERVA CANCELADA!</b></h1>
        </td>
    </tr>

    <tr>    
        <td style="padding-left: 35px; padding-right: 35px;">
            <p style="text-align: justify; font-size: 20px;line-height: 90%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 60px;margin-bottom: 32px;">Acabas de cancelar la reserva que tenias para entrenar.</p>
        </td>
    </tr>

    <tr>
        <td style="background-color: #dfdfdb; border-radius: 8px;padding-left: 35px; padding-right: 35px;">
        <p style="text-align: center; font-size: 26px;line-height: 90%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 15px;margin-bottom: 12px;"><b><?php echo $date;?> <a>/ <?php echo $hour;?></a> </b></p>
        <p style="text-align: center; font-size: 20px;line-height: 90%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 15px;margin-bottom: 12px;"><?php echo $address_line;?></p>
        <p style="text-align: center; font-size: 20px;line-height: 90%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 15px;margin-bottom: 12px;">Código de reserva: <?php echo $id_reserva;?></p>
        </td>
    </tr>
    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">
        <p style="text-align: justify; font-size: 20px;line-height: 90%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 59px;margin-bottom: 12px;">Esta reserva estaba a nombre de:</p>
        </td>
    </tr>

    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">
            <p style="text-align: justify; font-size: 20px;line-height: 90%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 10px;margin-bottom: 12px;"><b><?php echo $name;?></b></p>
            <p style="text-align: justify; font-size: 20px;line-height: 90%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: -4px;margin-bottom: 12px;"><b>Documento: <?php echo $document;?></b></p>
        </td>
    </tr>

    <tr>
        <td style="padding-left: 35px; padding-right: 35px;">
            <p style="font-size: 20px;line-height: 90%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 60px;margin-bottom: 12px;"><b>TE RECORDAMOS QUE: </b></p>
            <p style="text-align: justify; font-size: 18px;line-height: 125%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: -4px;margin-bottom: 12px;"> Puedes ingresar a la sede 10 minutos antes de la hora de tu reserva o hasta media hora después. Si llegas luego de tu hora perderás tu cupo.</p>
            <p style="text-align: justify; font-size: 18px;line-height: 125%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 7px;margin-bottom: 12px;">Una vez ingreses a la sede tienes 60 minutos para realizar tu entrenamiento.</p>
            <p style="text-align: justify; font-size: 18px;line-height: 125%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 7px;margin-bottom: 12px;">Para ingresar a la sede a través del torniquete debes descargar el código QR en la aplicación BODYTECH.</p>
            <p style="text-align: justify; font-size: 18px;line-height: 125%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 7px;margin-bottom: 12px;">En caso que no hayamos podido realizar el débito de tu plan, para hacer uso de tu reserva deberás acercarte al counter previamente y actualizar los datos.</p>
            <p style="text-align: justify; font-size: 18px;line-height: 125%;color: #3C3C3B;font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;margin-top: 7px;margin-bottom: 67px;">Para ver todas tus reservas puedes ingresar a la sección de mis reservas en tu cuenta. Ver mis reservas.</p>
        </td>
    </tr>

    <tr>
        <td>
            <table cellpadding="0" cellspacing="25" width="25%" align="center"  height="50">
                <tr>
                    <td></td>
                    <td><a href="#" target="_blank"><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/ico_android.jpg"></a></td>
                    <td><a href="#" target="_blank" ><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/ico_apple.jpg"></a></td>
                </tr>
            </table>
        </td>
    </tr>

    <tr>
        <td align="center" style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;">
            <a href="https://bodytech.com.co/perfil" target="_blank"  style="background-color: #DD702B;border: none;color: white;padding: 15px 32px;text-align: center;text-decoration: none;display: inline-block;font-size: 16px;border-radius: 6px;width: 250px;margin-bottom: 66px;margin-top: -7px;"><b>DESCARGALA YA!</b></a>
        </td>
    </tr>

    <tr>
        <td style="background-color: #dfdfdb; border-radius: 8px;"> 
            <table cellpadding="0" cellspacing="0" width="87%" align="center">
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" width="80%" align="center"  height="90">
                            <tr>
                                <td width="50%" style="text-align: right;">
                                    <a href="https://bodytech.com.co/" target="_black" style="text-decoration: none;"><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/thumbnail_logo_BW.png" style="width: 99px;"></a>
                                </td>
                                <td width="50%" style="text-align: left;">
                                    <a href="https://bodytech.com.co/" target="_black" style="color: black; text-decoration: none;">.com.co</a> 
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" width="70%" align="center" height="50">
                            <tr>
                                <td><a href="https://bodytech.com.co/planes/en-sede" target="_blank" style="color: black;text-decoration: none;">PRECIOS</a></td>
                                <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                <td><a href="https://bodytech.com.co/sedes" target="_blank" style="color: black;text-decoration: none;">SEDES</a></td>
                                <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                <td><a href="https://bodytech.com.co/doctor-bodytech" target="_blank" style="color: black;text-decoration: none;">DR. BODYTECH</a></td>
                                <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                <td><a href="https://bodytech.com.co/contacto" target="_blank" style="color: black;text-decoration: none;">CONTACTO</a></td>
                            </tr>
                        </table>
                    </td>
                </tr>                    
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" width="25%" align="center"  height="90">
                            <tr>
                                <td><a href="https://www.facebook.com/clubbodytech" target="_blank"><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/thumbnail_ico_fb.png"></a></td>
                                <td><a href="https://www.instagram.com/ClubBODYTECH/" target="_blank" ><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/thumbnail_ico_ig.png"></a></td>
                                <td><a href="https://twitter.com/ClubBODYTECH" target="_blank"><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/thumbnail_ico_tw.png"></a></td>
                                <td><a href="https://www.youtube.com/channel/UCcBV2tUbfK8Esy5QjvraupQ" target="_blank"><img src="https://bodytech-correo.s3-us-west-2.amazonaws.com/thumbnail_ico_yt.png"></a></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 11px;line-height: 23px;color: #3C3C3B;text-align: justify;">© 2021 BODYTECH es una marca registrada de BODYTECH Corp en Colombia y Perú. Todos los derechos reservados.</p>
                        <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 11px;line-height: 23px;color: #3C3C3B;text-align: justify;"></p>
                        <p></p>
                        <p style="font-family: 'Helvetica Neue', Helvetica, Roboto, sans-serif !important;font-style: normal;font-weight: normal;font-size: 11px;line-height: 23px;color: #3C3C3B;text-align: justify;">Si necesitas ayuda o tienes alguna pregunta, ponte en contacto con el Servicio de atención al cliente de Bodytech: en Bogotá: <a style="color:#D58C0B" ;>742 26 39</a>, Línea nacional <a style="color:#D58C0B" ;>01 8000 182 639</a> o WhatsApp <a style="color:#D58C0B" ;>322 800 0000 </a><br>Este mensaje es de caracter informativo<br><br> </p>
                        <p></p>
                    </td>
                </tr>
            </table>

        </td>
    </tr>
</table>






